// Osmanlı Padişahları Kart Seti — Veri Dosyası
// 36 padişah, quiz soruları, rozet tanımları

const DONEMLER = {
  kurulus:   { ad: "Kuruluş Dönemi",   renk: "#22c55e", ikon: "🌱", yillar: "1299–1453" },
  yukselis:  { ad: "Yükseliş Dönemi",  renk: "#f59e0b", ikon: "⚔️", yillar: "1453–1579" },
  duraklama: { ad: "Duraklama Dönemi", renk: "#3b82f6", ikon: "⚖️", yillar: "1579–1699" },
  gerileme:  { ad: "Gerileme Dönemi",  renk: "#a855f7", ikon: "📉", yillar: "1699–1828" },
  dagilma:   { ad: "Dağılma Dönemi",   renk: "#ef4444", ikon: "🏚️", yillar: "1828–1922" }
};

const SULTANLAR = [
  {
    id: "osman-gazi",
    sira: 1,
    ad: "Osman Gazi",
    lakap: "Koca Çınarın Tohumu",
    saltanat: "1299–1326",
    donem: "kurulus",
    biyografi: "Ertuğrul Gazi'nin oğlu. 3 kıta 7 iklime hakim olacak bir cihan devletinin temellerini attı, devleti adalet, meşveret ve hoşgörü üzerine kurarak halkına güven, düşmanına korku saldı.",
    olaylar: ["Koyunhisar Savaşı (1302)", "Osmanlı Beyliği'nin kuruluşu (1299)", "Karacahisar'ın fethi"],
    eserler: [],
    ilkler: ["Osmanlı Devleti'nin kurucusu"],
    istatistik: { saltanatYil: 27, fetihler: 5 },
    baba: null,
    biliyorMuydun: "Osman Gazi'nin gördüğü rüyada göbeğinden çıkan çınar ağacı tüm dünyayı kaplamıştır. Şeyh Edebali bu rüyayı büyük bir devletin kurulacağı şeklinde yorumlamıştır."
  },
  {
    id: "orhan-gazi",
    sira: 2,
    ad: "Orhan Gazi",
    lakap: "Koca Çınarın Rumeli'ye Uzanan Dalları",
    saltanat: "1326–1362",
    donem: "kurulus",
    biyografi: "Babası Osman Gazi'nin kurduğu devleti daha da büyüttü. İlk düzenli orduyu kurdu, Bursa'yı fethedip Osmanlı'nın ilk başkenti yaptı. Fetihlerle İslamiyet Rumeli topraklarına kadar ulaştı.",
    olaylar: ["Bursa'nın fethi (1326)", "İznik'in fethi (1331)", "Rumeli'ye geçiş (1354)"],
    eserler: ["Bursa Orhan Gazi Camii"],
    ilkler: ["İlk düzenli Osmanlı ordusu", "İlk Osmanlı başkenti Bursa"],
    istatistik: { saltanatYil: 36, fetihler: 8 },
    baba: "osman-gazi",
    biliyorMuydun: "Orhan Gazi, ilk Osmanlı akçesini bastıran padişahtır. Ayrıca ilk Osmanlı medresesini Bursa'da kurdurmuştur."
  },
  {
    id: "murad-1",
    sira: 3,
    ad: "Sultan I. Murad",
    lakap: "Hüdavendigâr — Şehid Padişah",
    saltanat: "1362–1389",
    donem: "kurulus",
    biyografi: "İlk kez 'sultan' unvanını kullandı ve devleti Balkanlar'da kalıcı bir güç haline getirdi. Osmanlı topraklarını Balkanlar'a doğru genişletti, Edirne'yi fethederek başkent yaptı, Sırpsındığı zaferiyle tüm Balkanlar'a adını duyurdu. Kosova Savaşı'nı kazandıktan sonra savaş alanında şehid edildi. Şehid olan ilk padişahtır.",
    olaylar: ["Edirne'nin fethi (1363)", "Sırpsındığı Savaşı (1364)", "I. Kosova Savaşı (1389)"],
    eserler: ["Edirne sarayı"],
    ilkler: ["'Sultan' unvanını kullanan ilk padişah", "Savaş alanında şehid olan ilk padişah", "Devşirme sisteminin kurucusu"],
    istatistik: { saltanatYil: 27, fetihler: 12 },
    baba: "orhan-gazi",
    biliyorMuydun: "I. Murad, Kosova Savaşı'nı kazandıktan sonra savaş alanını gezerken Sırp asilzadesi Miloş Obiliç tarafından şehid edilmiştir."
  },
  {
    id: "bayezid-1",
    sira: 4,
    ad: "Sultan I. Bayezid",
    lakap: "Yıldırım",
    saltanat: "1389–1402",
    donem: "kurulus",
    biyografi: "Savaş meydanlarında, orduları sevk ederken yıldırım gibi hızlıydı. İstanbul'u fethedebilmek için Anadolu Hisarını yaptı ve İstanbul'u 4 defa kuşattı ama fetih nasib olmadı. Niğbolu'da düşmanı yerle bir etti. Anadolu'da Türk beyliklerini Osmanlı'ya katarak Anadolu birliğini sağlamaya çalıştı ancak Ankara Savaşı'nda Emir Timur'a esir düştü ve o sırada şehid oldu.",
    olaylar: ["Niğbolu Savaşı (1396)", "Anadolu Hisarı inşası", "İstanbul'un 4 kez kuşatılması", "Ankara Savaşı (1402)"],
    eserler: ["Anadolu Hisarı", "Bursa Ulu Camii"],
    ilkler: ["Anadolu birliğini sağlamaya çalışan ilk padişah"],
    istatistik: { saltanatYil: 13, fetihler: 10 },
    baba: "murad-1",
    biliyorMuydun: "Yıldırım Bayezid, ordularını o kadar hızlı sevk ederdi ki düşmanları onun nasıl bu kadar çabuk geldiğine şaşırır, bu yüzden 'Yıldırım' lakabını almıştır."
  },
  {
    id: "mehmed-1",
    sira: 5,
    ad: "Sultan I. Mehmed",
    lakap: "Çelebi — İkinci Kurucu",
    saltanat: "1413–1421",
    donem: "kurulus",
    biyografi: "Timur'dan sonra dağılan Osmanlı devleti 11 sene boyunca bir ayrılığa düştü. Fetret Devri denilen bu döneme son verdi, devleti yeniden ayağa kaldırdı. Kaybedilen toprakları geri aldı, dağılan Anadolu beyliklerini Osmanlı devletine tekrar bağladı ve yaraları sarmaya muvaffak oldu. Bu kargaşayı sona erdirip devlete birlik ve düzen kazandırdığı için 'İkinci Kurucu' olarak anıldı. Osmanlı tarihinin ilk deniz savaşını Venediklilerle yaptı.",
    olaylar: ["Fetret Devri'ne son verilmesi (1413)", "Venediklilerle ilk deniz savaşı"],
    eserler: ["Bursa Yeşil Camii", "Yeşil Türbe"],
    ilkler: ["Fetret Devri'ni bitiren padişah", "İlk Osmanlı deniz savaşı"],
    istatistik: { saltanatYil: 8, fetihler: 4 },
    baba: "bayezid-1",
    biliyorMuydun: "Çelebi Mehmed, 11 yıl süren Fetret Devri'nde kardeşleriyle mücadele ederek devleti yeniden birleştirmiş, bu nedenle 'İkinci Kurucu' lakabını almıştır."
  },
  {
    id: "murad-2",
    sira: 6,
    ad: "Sultan II. Murad",
    lakap: "Tahtı Oğluna Bırakan Baba",
    saltanat: "1421–1451",
    donem: "kurulus",
    biyografi: "Balkanlarda pek çok zafer kazandı. Varna ve II. Kosova savaşlarında Osmanlı'yı zaferlere taşıdı. İstanbul'u kuşatarak Peygamber Efendimizin hadis-i şerifine nail olmak istedi lakin nasib olmadı. Tahtı bir süre oğlu Sultan Mehmed'e bıraktı ama zor zamanlarda yeniden dönüp devleti savundu.",
    olaylar: ["Varna Savaşı (1444)", "II. Kosova Savaşı (1448)", "İstanbul kuşatması"],
    eserler: ["Edirne Muradiye Camii"],
    ilkler: ["Tahtı kendi isteğiyle bırakan ilk padişah"],
    istatistik: { saltanatYil: 30, fetihler: 9 },
    baba: "mehmed-1",
    biliyorMuydun: "II. Murad, tahtı oğlu Fatih Sultan Mehmed'e bırakıp Manisa'ya çekilmiş, ancak Haçlı saldırıları üzerine tekrar tahta çıkmak zorunda kalmıştır."
  },
  {
    id: "fatih-sultan-mehmed",
    sira: 7,
    ad: "Fatih Sultan Mehmed",
    lakap: "Çağ Açıp Çağ Kapatan Fatih",
    saltanat: "1451–1481",
    donem: "yukselis",
    biyografi: "Çocukluğundan beri İstanbul'un fetihini hayal etti. Padişah olduktan sonra fetih için Rumeli Hisarını yaptı, şahi toplar döktürdü ve İstanbul'u fethederek çağ açıp çağ kapadı, Hazret-i Peygamber'in müjdesine kavuştu. Nice fetihlerle 17 devleti Osmanlı'ya kattı, 'Kayzer-i Rum' olarak şöhret kazandı. İlim ve sanatın büyük hamisi oldu.",
    olaylar: ["İstanbul'un Fethi (1453)", "Rumeli Hisarı inşası", "17 devletin fethi", "Trabzon Rum İmparatorluğu'nun sonu"],
    eserler: ["Rumeli Hisarı", "Fatih Camii", "Topkapı Sarayı"],
    ilkler: ["İstanbul'u fetheden padişah", "Çağ değiştiren fetih"],
    istatistik: { saltanatYil: 30, fetihler: 17 },
    baba: "murad-2",
    biliyorMuydun: "Fatih Sultan Mehmed 7 dil biliyordu: Türkçe, Arapça, Farsça, Latince, Yunanca, İbranice ve Slavca. Ayrıca 'Avnî' mahlasıyla şiirler yazmıştır."
  },
  {
    id: "bayezid-2",
    sira: 8,
    ad: "Sultan II. Bayezid",
    lakap: "Bayezid-i Velî — Barışsever Padişah",
    saltanat: "1481–1512",
    donem: "yukselis",
    biyografi: "Barış isteyen bir padişahtı. Saltanatının başında kardeşi Cem Sultan'la uğraştı. Donanmayı güçlendirdi. Endülüs'te zulüm gören Müslümanları Osmanlı topraklarına getirdi. Mora ve Boğdan'da fetihlerde bulundu. 'Bayezid-i Veli' olarak anıldı.",
    olaylar: ["Cem Sultan olayı", "Endülüs Müslümanlarının kurtarılması", "Mora ve Boğdan fetihleri"],
    eserler: ["İstanbul Bayezid Camii", "Edirne Bayezid Külliyesi"],
    ilkler: ["Endülüs'ten Müslümanları kurtaran padişah"],
    istatistik: { saltanatYil: 31, fetihler: 6 },
    baba: "fatih-sultan-mehmed",
    biliyorMuydun: "II. Bayezid, İspanya'da zulüm gören Yahudileri de Osmanlı topraklarına kabul etmiş, onlara sığınma hakkı tanımıştır."
  },
  {
    id: "yavuz-sultan-selim",
    sira: 9,
    ad: "Yavuz Sultan Selim",
    lakap: "Kükreyen Aslan, Kutsal Emanetlerin Hamisi",
    saltanat: "1512–1520",
    donem: "yukselis",
    biyografi: "Cihangir bir padişahtı. Çaldıran'da Osmanlı için büyük tehlike olan Safevileri bozguna uğrattı, Mercidabık ve Ridaniye zaferleriyle Memlükleri tarih sahnesinden sildi. Hilafeti Osmanlı'ya taşıyarak İslam dünyasının lideri oldu. Sert mizacı ve kararlılığıyla tanındı. Osmanlı'yı dünyanın en büyük gücü haline getirdi. Şah İsmail ile savaşıp Anadolu'nun şiileşmesinin önüne geçti.",
    olaylar: ["Çaldıran Savaşı (1514)", "Mercidabık Savaşı (1516)", "Ridaniye Savaşı (1517)", "Hilafet'in Osmanlı'ya geçişi"],
    eserler: ["Yavuz Sultan Selim Camii"],
    ilkler: ["Hilafeti Osmanlı'ya taşıyan padişah", "Osmanlı topraklarını en çok genişleten padişah"],
    istatistik: { saltanatYil: 8, fetihler: 14 },
    baba: "bayezid-2",
    biliyorMuydun: "Yavuz Sultan Selim sadece 8 yıl tahtta kalmış ama bu sürede Osmanlı topraklarını 2,5 kat büyütmüştür. Ayrıca şair bir padişahtı ve Farsça divanı vardır."
  },
  {
    id: "kanuni-sultan-suleyman",
    sira: 10,
    ad: "Kanuni Sultan Süleyman",
    lakap: "Muhteşem Süleyman",
    saltanat: "1520–1566",
    donem: "yukselis",
    biyografi: "46 yıl tahtta kalarak Osmanlı'nın en uzun süre hüküm süren padişahı oldu. Mohaç Zaferi, Belgrad ve Rodos'un fethiyle Avrupa'yı sarstı. Bağdat ve Tebriz'i alarak doğuda da Safeviler'e darbe vurdu. 72 yaşında Zigetvar Seferi sırasında vefat etti. Kanunlara olan bağlılığı sebebiyle 'Kanuni' unvanını aldı. Süleymaniye Külliyesi ve daha nice muhteşem eserleri Osmanlı Devletine kazandırdı.",
    olaylar: ["Belgrad'ın fethi (1521)", "Rodos'un fethi (1522)", "Mohaç Savaşı (1526)", "I. Viyana Kuşatması (1529)", "Bağdat'ın fethi (1534)", "Zigetvar Seferi (1566)"],
    eserler: ["Süleymaniye Külliyesi", "Şehzadebaşı Camii"],
    ilkler: ["En uzun süre tahtta kalan padişah (46 yıl)", "Batı'da 'Muhteşem' lakabıyla bilinen padişah"],
    istatistik: { saltanatYil: 46, fetihler: 20 },
    baba: "yavuz-sultan-selim",
    biliyorMuydun: "Kanuni Sultan Süleyman 'Muhibbi' mahlasıyla 3.000'den fazla şiir yazmıştır. Batılılar ona 'Magnificent Suleiman' (Muhteşem Süleyman) derken, halkı onu adaleti sebebiyle 'Kanuni' olarak anmıştır."
  },
  {
    id: "selim-2",
    sira: 11,
    ad: "Sultan II. Selim",
    lakap: "Sarı Selim",
    saltanat: "1566–1574",
    donem: "yukselis",
    biyografi: "'Sarı Selim' diye anıldı. Osmanlı donanması onun zamanında daha da güçlendi ve Kıbrıs'ı fethetti. Osmanlı Devletinin gücünü Endonezya'ya kadar genişletti. Başarısız da olsa Don-Volga kanalı projesi gibi önemli projelere imza attı. İnebahtı Savaşı bu padişah devrinde yapıldı.",
    olaylar: ["Kıbrıs'ın fethi (1571)", "İnebahtı Savaşı (1571)", "Don-Volga kanal projesi"],
    eserler: ["Edirne Selimiye Camii (Mimar Sinan eseri)"],
    ilkler: ["Don-Volga kanalı projesini başlatan padişah"],
    istatistik: { saltanatYil: 8, fetihler: 4 },
    baba: "kanuni-sultan-suleyman",
    biliyorMuydun: "II. Selim döneminde Mimar Sinan'ın ustalık eseri Selimiye Camii inşa edilmiştir. Mimar Sinan bu camiyi 'ustalık eserim' olarak tanımlamıştır."
  },
  {
    id: "murad-3",
    sira: 12,
    ad: "Sultan III. Murad",
    lakap: "Şair Padişah",
    saltanat: "1574–1595",
    donem: "duraklama",
    biyografi: "Döneminde Osmanlı geniş sınırlara ulaşmaya devam etti. İran ve Avusturya ile uzun savaşlar yapıldı. Sadrazam olan Sokullu Mehmed Paşa'nın vefatıyla devlet işlerinde zayıflama başladı. Celali isyanlarıyla uğraştı. İlk rasathane bu dönemde yapıldı. Osmanlı padişahları arasında en fazla şiir yazan padişahtır.",
    olaylar: ["Sokullu Mehmed Paşa'nın vefatı (1579)", "İran savaşları", "Celali isyanları"],
    eserler: ["İstanbul Rasathanesi (Takiyüddin)"],
    ilkler: ["En çok şiir yazan padişah", "İlk rasathane bu dönemde kuruldu"],
    istatistik: { saltanatYil: 21, fetihler: 5 },
    baba: "selim-2",
    biliyorMuydun: "III. Murad döneminde kurulan İstanbul Rasathanesi, Avrupa'daki rasathanelerden çok daha gelişmişti ancak kısa süre sonra yıktırılmıştır."
  },
  {
    id: "mehmed-3",
    sira: 13,
    ad: "Sultan III. Mehmed",
    lakap: "Adlî",
    saltanat: "1595–1603",
    donem: "duraklama",
    biyografi: "Döneminde Safeviler ve Avusturya ile yapılan uzun savaşlar devam etti. 1596'da Haçova Meydan Savaşı'nda büyük bir zafer kazandı.",
    olaylar: ["Haçova Meydan Savaşı (1596)", "Eğri Kalesi'nin fethi (1596)"],
    eserler: [],
    ilkler: ["Sefere bizzat çıkan son padişahlardan biri"],
    istatistik: { saltanatYil: 8, fetihler: 3 },
    baba: "murad-3",
    biliyorMuydun: "III. Mehmed, Haçova Savaşı'nda bizzat ordunun başında bulunmuş ve bu zafer sayesinde Osmanlı, Macaristan'daki varlığını sürdürmüştür."
  },
  {
    id: "ahmed-1",
    sira: 14,
    ad: "Sultan I. Ahmed",
    lakap: "Sultanahmet Camii'nin Banisi",
    saltanat: "1603–1617",
    donem: "duraklama",
    biyografi: "Genç yaşta tahta çıktı. Şehzade katli geleneğini kaldırdı. Böylece kardeş katli sona erdi. Celali isyanlarını, Avusturya ve İran savaşlarını başarıyla bitirdi. İstanbul'un en güzel eserlerinden biri olan Sultanahmet Camisini yaptırdı. Genç yaşında vefat etti. Şair padişahlardan birisiydi.",
    olaylar: ["Şehzade katli geleneğinin kaldırılması", "Celali isyanlarının bastırılması", "Zitvatorok Antlaşması (1606)"],
    eserler: ["Sultanahmet Camii (Mavi Cami)"],
    ilkler: ["Şehzade katli geleneğini kaldıran padişah"],
    istatistik: { saltanatYil: 14, fetihler: 2 },
    baba: "mehmed-3",
    biliyorMuydun: "I. Ahmed, Sultanahmet Camii'nin inşaatında bizzat çalışarak taş taşımıştır. Cami, 6 minaresiyle İstanbul'un simgesi haline gelmiştir."
  },
  {
    id: "mustafa-1",
    sira: 15,
    ad: "Sultan I. Mustafa",
    lakap: "Kalbi Yumuşak, Bahtı Garip Padişah",
    saltanat: "1617–1618; 1622–1623",
    donem: "duraklama",
    biyografi: "İki kez tahta çıktı. Ancak akli dengesi yerinde olmadığı için devlet işlerini yürütemedi. Çevresindekilerin tesiri altında kaldı, isyanlar arttı.",
    olaylar: ["İki kez tahta çıkması", "Kısa saltanat dönemleri"],
    eserler: [],
    ilkler: ["İki kez tahta çıkan ilk padişah"],
    istatistik: { saltanatYil: 2, fetihler: 0 },
    baba: "mehmed-3",
    biliyorMuydun: "I. Mustafa, uzun yıllar kafes hayatı yaşamış ve bu durum ruh sağlığını ciddi şekilde etkilemiştir."
  },
  {
    id: "osman-2",
    sira: 16,
    ad: "Sultan II. Osman",
    lakap: "Genç Osman — Şehid Padişah",
    saltanat: "1618–1622",
    donem: "duraklama",
    biyografi: "14 yaşında tahta çıktı, cesur ve atılgandı. Okçulukta çok ustaydı. Yeniçerileri ıslah etmek istedi. Tecrübesizliği sebebiyle Yeniçerileri karşısına aldı ve 18 yaşında Yeniçerilerin isyanıyla öldürüldü. Osmanlı tarihinde bir darbe sebebiyle şehit edilen ilk padişah oldu.",
    olaylar: ["Hotin Seferi (1621)", "Yeniçeri isyanı (1622)"],
    eserler: [],
    ilkler: ["Darbe ile şehid edilen ilk padişah"],
    istatistik: { saltanatYil: 4, fetihler: 1 },
    baba: "ahmed-1",
    biliyorMuydun: "Genç Osman, Yeniçeri Ocağı'nı kaldırıp yerine yeni bir ordu kurmayı planlamış, ancak bu planı öğrenilince Yeniçeriler tarafından şehid edilmiştir."
  },
  {
    id: "murad-4",
    sira: 17,
    ad: "Sultan IV. Murad",
    lakap: "Bileği Bükülmez, Kudretli Padişah",
    saltanat: "1623–1640",
    donem: "duraklama",
    biyografi: "11 yaşında tahta çıktı, 18 yaşında tahta tamamen hakim oldu ve devleti toparladı. İnanılmaz derecede fizik gücüyle efsaneleşmiş bir hükümdardı. Disiplini ve sertliğiyle devlet yönetimini zorlaştıran kişileri toparladı. İçki, tütün ve gece sokağa çıkmayı yasakladı. Revan ve Bağdat seferleriyle doğuda Osmanlı hâkimiyetini pekiştirdi.",
    olaylar: ["Revan Seferi (1635)", "Bağdat Seferi (1638)", "İçki ve tütün yasağı"],
    eserler: ["Revan Köşkü (Topkapı Sarayı)", "Bağdat Köşkü"],
    ilkler: ["Fizik gücüyle efsaneleşen padişah"],
    istatistik: { saltanatYil: 17, fetihler: 6 },
    baba: "ahmed-1",
    biliyorMuydun: "IV. Murad'ın fiziksel gücü efsaneydi; 200 kiloluk gürzü tek eliyle savurabildiği, ok ile zırhı deldiği rivayet edilir. Ayrıca sefere bizzat çıkan son padişahlardan biridir."
  },
  {
    id: "ibrahim",
    sira: 18,
    ad: "Sultan İbrahim",
    lakap: "Zor Günlere Rağmen Devletini Ayakta Tutan Sultan",
    saltanat: "1640–1648",
    donem: "duraklama",
    biyografi: "Uzun yıllar kafeste yaşadığı için ruhen yıpranmış, hassas bir mizaca sahipti. Saltanatında valide sultan ve saray çevresinin nüfuzu arttı. Devleti en iyi şekilde yönetmeye çalıştı ve beraber hayır eserleri ve vakıflar kurdurdu. İç karışıklıkların büyümesiyle tahttan indirildi ve şehid edildi.",
    olaylar: ["Girit Seferi'nin başlaması (1645)", "Saray nüfuzunun artması"],
    eserler: ["Çeşitli vakıflar ve hayır eserleri"],
    ilkler: [],
    istatistik: { saltanatYil: 8, fetihler: 2 },
    baba: "ahmed-1",
    biliyorMuydun: "Sultan İbrahim, kardeşi IV. Murad'ın vefatından sonra Osmanlı hanedanından hayatta kalan tek erkek olarak tahta çıkmıştır."
  },
  {
    id: "mehmed-4",
    sira: 19,
    ad: "Sultan IV. Mehmed",
    lakap: "Avcı Sultan",
    saltanat: "1648–1687",
    donem: "duraklama",
    biyografi: "Çocuk yaşta tahta çıktı ve uzun süre tahtta kaldı. Köprülü ailesinin sadrazamlığıyla Osmanlı'ya yeniden düzen geldi. Girit fethedildi ve Akdeniz hakimiyetimiz güçlendi, Uyvar gibi önemli yerler fethedildi. 1683 yılında Viyana önlerine kadar gidildi ve Viyana ikinci kez kuşatıldı.",
    olaylar: ["Köprülü dönemi", "Girit'in fethi (1669)", "II. Viyana Kuşatması (1683)", "Uyvar'ın fethi"],
    eserler: [],
    ilkler: ["Çocuk yaşta tahta çıkıp en uzun süre kalan padişahlardan biri"],
    istatistik: { saltanatYil: 39, fetihler: 8 },
    baba: "ibrahim",
    biliyorMuydun: "IV. Mehmed av merakıyla tanınırdı ve 'Avcı Sultan' lakabını almıştır. Edirne'de uzun süre kalarak av partileri düzenlemiştir."
  },
  {
    id: "suleyman-2",
    sira: 20,
    ad: "Sultan II. Süleyman",
    lakap: "Sıkıntılı Günlerin Padişahı",
    saltanat: "1687–1691",
    donem: "duraklama",
    biyografi: "Uzun yıllar kafeste yaşadığı için kırılgan bir mizaca sahipti. Tahta çıktığında Osmanlı zor durumdaydı. Devletin toparlanmasında asıl rolü Köprülüzade Fazıl Mustafa Paşa üstlendi. Devlet sıkıntılı günlerden geçti ve 4 yıl tahtta kaldıktan sonra vefat etti.",
    olaylar: ["Köprülüzade Fazıl Mustafa Paşa'nın sadrazamlığı", "Avusturya savaşları"],
    eserler: [],
    ilkler: [],
    istatistik: { saltanatYil: 4, fetihler: 1 },
    baba: "ibrahim",
    biliyorMuydun: "II. Süleyman, 44 yıl kafes hayatı yaşadıktan sonra tahta çıkmıştır. Tahta çıktığında ilk sözü 'Beni öldürecekseniz söyleyin, hazırlanayım' olmuştur."
  },
  {
    id: "ahmed-2",
    sira: 21,
    ad: "Sultan II. Ahmed",
    lakap: "Devleti Savunan Padişah",
    saltanat: "1691–1695",
    donem: "duraklama",
    biyografi: "Devletin zor günlerinde Avusturya'ya karşı Belgrad'ı savundu, kutsal ittifakla savaşlar devam etti. Sadrazam Fazıl Mustafa Paşa'nın üstün gayretiyle Osmanlı ordusu bir süre toparlandı. Fakat Fazıl Mustafa Paşa'nın vefatıyla Osmanlı ordusu tekrar zayıfladı ve düşmanları karşısında güç kaybetti.",
    olaylar: ["Slankamen Savaşı (1691)", "Belgrad savunması"],
    eserler: [],
    ilkler: [],
    istatistik: { saltanatYil: 4, fetihler: 1 },
    baba: "ibrahim",
    biliyorMuydun: "II. Ahmed döneminde Sadrazam Fazıl Mustafa Paşa, Slankamen Savaşı'nda şehid düşmüş ve bu kayıp Osmanlı ordusunu derinden sarsmıştır."
  },
  {
    id: "mustafa-2",
    sira: 22,
    ad: "Sultan II. Mustafa",
    lakap: "Rahatı Kendine Haram Kılan Padişah",
    saltanat: "1695–1703",
    donem: "gerileme",
    biyografi: "Savaş meydanında ordunun başında bulunmayı seven bir padişahtı. Devlet zor günlerden geçerken bir çok savaşa giriyordu. Zenta Muharebesinin kaybıyla devlet daha da zayıfladı. 1699 Karlofça Antlaşması'yla Osmanlı ilk kez geniş toprak kayıplarına uğradı. Karlofça ile Osmanlı'nın Avrupa karşısındaki üstünlüğü sona erdi.",
    olaylar: ["Zenta Muharebesi (1697)", "Karlofça Antlaşması (1699)", "Edirne Vakası (1703)"],
    eserler: [],
    ilkler: ["Karlofça ile ilk büyük toprak kaybı"],
    istatistik: { saltanatYil: 8, fetihler: 2 },
    baba: "mehmed-4",
    biliyorMuydun: "II. Mustafa, 'Rahatı kendimize haram kıldık' diyerek ordunun başına geçmiş ve bizzat seferlere çıkmıştır. Ancak Karlofça Antlaşması Osmanlı tarihinin en acı dönüm noktalarından biri olmuştur."
  },
  {
    id: "ahmed-3",
    sira: 23,
    ad: "Sultan III. Ahmed",
    lakap: "Lale Devri'nin Padişahı",
    saltanat: "1703–1730",
    donem: "gerileme",
    biyografi: "Lale Devri'nin padişahıdır. Lale Devrinde sanat, edebiyat ve mimaride büyük gelişmeler yaşandı; Sadabad Kasırları yapıldı, matbaa kuruldu. Bu dönemde devlet savaşlardan uzak durdu ve sanat, edebiyat gibi alanlara daha da önem verdi. Bu gelişmelerle Osmanlı güç kazandı ancak Patrona Halil İsyanı ile devri sona erdi.",
    olaylar: ["Lale Devri (1718–1730)", "İlk matbaanın kurulması (1727)", "Patrona Halil İsyanı (1730)", "Prut Savaşı (1711)"],
    eserler: ["Sadabad Kasırları", "III. Ahmed Çeşmesi"],
    ilkler: ["İlk Osmanlı matbaası bu dönemde kuruldu"],
    istatistik: { saltanatYil: 27, fetihler: 3 },
    baba: "mehmed-4",
    biliyorMuydun: "Lale Devri'nde İstanbul'da lale yetiştirme çılgınlığı yaşanmış, gece lale bahçelerinde kaplumbağaların sırtına mum bağlanarak aydınlatma yapılmıştır."
  },
  {
    id: "mahmud-1",
    sira: 24,
    ad: "Sultan I. Mahmud",
    lakap: "Düzeni Yeniden Kuran Padişah",
    saltanat: "1730–1754",
    donem: "gerileme",
    biyografi: "Patrona Halil İsyanı sonrası tahta çıktı. Kargaşa içerisinde olan devleti güçlü bir idareyle düzene soktu. Humbaracı Ahmet Paşa'nın öncülüğünde ıslahatlar yaptı. İran ve Avusturya savaşlarıyla uğraştı, genel olarak başarılı bir siyaset yürüttü.",
    olaylar: ["Patrona Halil İsyanı'nın bastırılması", "Humbaracı Ahmet Paşa ıslahatları", "İran ve Avusturya savaşları"],
    eserler: ["Nuruosmaniye Camii (inşası başlatıldı)"],
    ilkler: ["Askeri ıslahatlar yapan ilk padişahlardan"],
    istatistik: { saltanatYil: 24, fetihler: 2 },
    baba: "mustafa-2",
    biliyorMuydun: "I. Mahmud, Fransız Comte de Bonneval'ı Müslüman yaparak 'Humbaracı Ahmet Paşa' adıyla Osmanlı ordusunda ıslahatlar yapmasını sağlamıştır."
  },
  {
    id: "osman-3",
    sira: 25,
    ad: "Sultan III. Osman",
    lakap: "Olumsuzluklara Rağmen Kararlılıkla Yöneten Merhametli Padişah",
    saltanat: "1754–1757",
    donem: "gerileme",
    biyografi: "51 yaşında tahta çıkmıştır. Döneminde olan çeşitli olumsuzluklarla uğraşmıştır. Sık sık tebdil-i kıyafet ile halkın içerisine karışmış, halkın sorunlarını dinlemiştir.",
    olaylar: ["Tebdil-i kıyafet ile halk arasına karışması", "İstanbul'daki yangınlarla mücadele"],
    eserler: ["Nuruosmaniye Camii (tamamlandı)"],
    ilkler: ["Halk arasına en çok karışan padişahlardan"],
    istatistik: { saltanatYil: 3, fetihler: 0 },
    baba: "mustafa-2",
    biliyorMuydun: "III. Osman, 50 yıldan fazla kafes hayatı yaşadıktan sonra tahta çıkmıştır. Tebdil-i kıyafet ile İstanbul sokaklarında dolaşıp halkın dertlerini dinlemeyi severdi."
  },
  {
    id: "mustafa-3",
    sira: 26,
    ad: "Sultan III. Mustafa",
    lakap: "Gayretli ve Çalışkan Padişah",
    saltanat: "1757–1774",
    donem: "gerileme",
    biyografi: "Gayretli, cesur ve çalışkan bir padişahtı. Rusya ile savaşlar onun devrinde şiddetlendi. Donanmayı ve orduyu güçlendirmeye çalıştı. Askeri modernleştirip, yeni okullar açarak Avrupa'yı yakalamak istedi. Astronomiye meraklıydı; yıldızları gözlemleyip rasathanelerden sık sık haberler alırdı. Ağır şartların olduğu Küçükkaynarca Antlaşması bu dönemde oldu.",
    olaylar: ["1768-1774 Osmanlı-Rus Savaşı", "Çeşme Baskını (1770)", "Küçük Kaynarca Antlaşması (1774)"],
    eserler: ["Laleli Camii", "Askeri okullar"],
    ilkler: ["Astronomiye en meraklı padişah"],
    istatistik: { saltanatYil: 17, fetihler: 1 },
    baba: "ahmed-3",
    biliyorMuydun: "III. Mustafa, astronomi ve yıldız bilimi ile çok ilgilenirdi. Sarayda özel bir gözlemevi kurdurup yıldız haritaları çıkartmıştır."
  },
  {
    id: "abdulhamid-1",
    sira: 27,
    ad: "Sultan I. Abdülhamid",
    lakap: "Islahatçı Padişah",
    saltanat: "1774–1789",
    donem: "gerileme",
    biyografi: "Döneminde Küçük Kaynarca Antlaşması sonrası büyük kayıplar yaşandı. Bu zorlu dönemlerde özellikle orduda ve maliyede ıslahatlar yaptı. 1787-1792 Osmanlı-Rus savaşında Özi Kalesi'nin Rusların eline geçtiği ve kale içindeki halkın Ruslar tarafından katledildiği haberini duyunca sağ tarafına felç geldi ve 64 yaşında iken 7 Nisan 1789'da vefat etti.",
    olaylar: ["Kırım'ın kaybedilmesi (1783)", "1787-1792 Osmanlı-Rus Savaşı", "Özi Kalesi felaketi"],
    eserler: ["Beylerbeyi Camii", "Hamidiye Külliyesi"],
    ilkler: ["Orduda ve maliyede kapsamlı ıslahatlar yapan padişah"],
    istatistik: { saltanatYil: 15, fetihler: 0 },
    baba: "ahmed-3",
    biliyorMuydun: "I. Abdülhamid, Özi Kalesi'ndeki katliamı duyunca felç geçirmiş ve kısa süre sonra vefat etmiştir. Bu olay onun ne kadar halkını düşünen bir padişah olduğunu gösterir."
  },
  {
    id: "selim-3",
    sira: 28,
    ad: "Sultan III. Selim",
    lakap: "Nizam-ı Cedid'in Kurucusu",
    saltanat: "1789–1807",
    donem: "gerileme",
    biyografi: "Nizam-ı Cedid ordusunu kurarak Osmanlı ordusuna yeni bir düzen getirdi. Döneminde bir çok alanda ıslahatlar yapıldı. Fransa, Avusturya ve Rusya ile savaşlar yapıldı. Kabakçı Mustafa İsyanı ile Yeniçeriler onu tahttan indirdi.",
    olaylar: ["Nizam-ı Cedid ordusunun kurulması", "Kabakçı Mustafa İsyanı (1807)", "Fransız Devrimi etkisi"],
    eserler: ["Nizam-ı Cedid kışlaları"],
    ilkler: ["Modern Osmanlı ordusunun ilk temellerini atan padişah"],
    istatistik: { saltanatYil: 18, fetihler: 0 },
    baba: "mustafa-3",
    biliyorMuydun: "III. Selim aynı zamanda bestekâr bir padişahtı. Türk müziğinde 'Suzidilara' makamını icat etmiş ve birçok eser bestelemiştir."
  },
  {
    id: "mustafa-4",
    sira: 29,
    ad: "Sultan IV. Mustafa",
    lakap: "Kısa Saltanatlı Padişah",
    saltanat: "1807–1808",
    donem: "gerileme",
    biyografi: "Tahta geçtikten sonra Nizam-ı Cedid ordusunu kaldırdı. Kısa süren saltanatında devleti yönetmekte yetersiz kaldı. Yine Alemdar Mustafa Paşa isyanlarında tahttan indirildi.",
    olaylar: ["Nizam-ı Cedid'in kaldırılması", "Alemdar Mustafa Paşa vakası (1808)"],
    eserler: [],
    ilkler: [],
    istatistik: { saltanatYil: 1, fetihler: 0 },
    baba: "abdulhamid-1",
    biliyorMuydun: "IV. Mustafa'nın saltanatı sadece 14 ay sürmüştür, bu da onu en kısa süre tahtta kalan padişahlardan biri yapmaktadır."
  },
  {
    id: "mahmud-2",
    sira: 30,
    ad: "Sultan II. Mahmud",
    lakap: "Islahatçı Padişah",
    saltanat: "1808–1839",
    donem: "dagilma",
    biyografi: "'Islahatçı Padişah' olarak tanındı. 1826'da Yeniçeri Ocağı'nı kaldırarak büyük bir reform yaptı. Batılı tarzda kıyafet ve idari düzenlemeler getirdi. Döneminde Tanzimat'ın temelleri atıldı ve birçok isyanla uğraşmıştır.",
    olaylar: ["Yeniçeri Ocağı'nın kaldırılması - Vaka-i Hayriye (1826)", "Yunan İsyanı", "Navarin Baskını (1827)", "Tanzimat'ın temelleri"],
    eserler: ["Asakir-i Mansure-i Muhammediye ordusu"],
    ilkler: ["Yeniçeri Ocağı'nı kaldıran padişah", "Fes giyen ilk padişah"],
    istatistik: { saltanatYil: 31, fetihler: 0 },
    baba: "abdulhamid-1",
    biliyorMuydun: "II. Mahmud, 1826'da Yeniçeri Ocağı'nı kaldırdığı olaya 'Vaka-i Hayriye' (Hayırlı Olay) adı verilmiştir. Ayrıca ilk nüfus sayımını yaptırmış ve posta teşkilatını kurmuştur."
  },
  {
    id: "abdulmecid",
    sira: 31,
    ad: "Sultan Abdülmecid",
    lakap: "Tanzimat'ın Padişahı",
    saltanat: "1839–1861",
    donem: "dagilma",
    biyografi: "Tahta çıktığında Gülhane Hatt-ı Hümayunu'nu (Tanzimat Fermanı) ilan etti ve Osmanlı'da modernleşme sürecini başlattı. Eğitim, hukuk ve idare alanlarında Batı tarzı yenilikler yapıldı. Dolmabahçe Sarayı'nı yaptırarak devletin merkezini değiştirdi. Genç yaşına rağmen yenilikçi ve idealist bir padişahtı. Mekke ve Medine'ye en çok hizmet eden padişahtır.",
    olaylar: ["Tanzimat Fermanı (1839)", "Islahat Fermanı (1856)", "Kırım Savaşı (1853-1856)"],
    eserler: ["Dolmabahçe Sarayı", "Bezmiâlem Valide Sultan Camii"],
    ilkler: ["Tanzimat Fermanı'nı ilan eden padişah", "Dolmabahçe Sarayı'nı yaptıran padişah"],
    istatistik: { saltanatYil: 22, fetihler: 0 },
    baba: "mahmud-2",
    biliyorMuydun: "Abdülmecid, Kırım Savaşı sırasında kendi cebinden İrlanda'ya yardım göndermiş, Kraliçe Victoria'nın 'çok fazla' dediği miktarı azaltmak zorunda kalmıştır."
  },
  {
    id: "abdulaziz",
    sira: 32,
    ad: "Sultan Abdülaziz",
    lakap: "Orduyu Güçlendirip Düşmana Kafa Tutan Şehid Sultan",
    saltanat: "1861–1876",
    donem: "dagilma",
    biyografi: "Batı'ya seyahat eden ilk Osmanlı padişahıdır. Donanmayı dünyanın en büyük 3. filosu haline getirdi. Ancak ekonomik sıkıntılar arttı, borçlanmalar çoğaldı. Eğitim, askeri ve ulaşımda birçok yenilik yapıldı. 1876 yılında şehid edildi.",
    olaylar: ["Avrupa seyahati (1867)", "Donanmanın güçlendirilmesi", "Ekonomik kriz", "Tahttan indirme ve şehadeti (1876)"],
    eserler: ["Çırağan Sarayı", "Beylerbeyi Sarayı"],
    ilkler: ["Avrupa'yı ziyaret eden ilk Osmanlı padişahı", "Donanmayı dünya 3.sü yapan padişah"],
    istatistik: { saltanatYil: 15, fetihler: 0 },
    baba: "mahmud-2",
    biliyorMuydun: "Sultan Abdülaziz, Osmanlı donanmasını dünyanın 3. büyük donanması haline getirmiştir. Ayrıca güreş meraklısıydı ve bizzat güreş tutardı."
  },
  {
    id: "murad-5",
    sira: 33,
    ad: "Sultan V. Murad",
    lakap: "93 Günlük Padişah",
    saltanat: "1876",
    donem: "dagilma",
    biyografi: "Sadece 93 gün tahtta kaldı. Ruhsal rahatsızlıkları nedeniyle devlet işlerini yürütemedi. Bu yüzden kısa sürede tahttan indirildi.",
    olaylar: ["93 günlük saltanat", "Tahttan indirilmesi"],
    eserler: [],
    ilkler: ["En kısa süre tahtta kalan padişahlardan"],
    istatistik: { saltanatYil: 0.25, fetihler: 0 },
    baba: "abdulmecid",
    biliyorMuydun: "V. Murad, batı müziğine çok düşkündü ve piyano çalardı. Meşrutiyet yanlısıydı ancak ruhsal sorunları nedeniyle tahtta kalamamıştır."
  },
  {
    id: "abdulhamid-2",
    sira: 34,
    ad: "Sultan II. Abdülhamid Han",
    lakap: "Ulu Hakan",
    saltanat: "1876–1909",
    donem: "dagilma",
    biyografi: "33 yıl tahtta kalarak en uzun süre hüküm süren Osmanlı padişahlarından biridir. Eğitim alanında büyük atılımlar yaptı; okullar, kütüphaneler, hastaneler açtı. Haberleşme ve ulaşımda (telgraf, demiryolu, özellikle Hicaz Demiryolu) büyük gelişmeler sağladı. Batılıların 'Kızıl Sultan' dediği bu padişah, halkı tarafından 'Ulu Hakan' olarak anıldı.",
    olaylar: ["I. Meşrutiyet (1876)", "93 Harbi (1877-78)", "Hicaz Demiryolu", "II. Meşrutiyet (1908)", "31 Mart Vakası (1909)"],
    eserler: ["Hicaz Demiryolu", "Hamidiye su şebekesi", "Yüzlerce okul ve hastane", "Yıldız Sarayı"],
    ilkler: ["En çok okul açan padişah", "Hicaz Demiryolu'nu yaptıran padişah"],
    istatistik: { saltanatYil: 33, fetihler: 0 },
    baba: "abdulmecid",
    biliyorMuydun: "II. Abdülhamid, marangozluk yaparak mobilyalar üretirdi. Sherlock Holmes romanlarının hayranıydı ve her yeni kitabını tercüme ettirirdi. 33 yılda 10.000'den fazla okul açtırmıştır."
  },
  {
    id: "mehmed-resad",
    sira: 35,
    ad: "Sultan Mehmed Reşad",
    lakap: "Hasta Adam Diyenlere Rağmen Düşmanı Yerle Bir Eden Sultan",
    saltanat: "1909–1918",
    donem: "dagilma",
    biyografi: "İttihat ve Terakki'nin gölgesinde hüküm sürdü. I. Dünya Savaşı'na Osmanlı onun zamanında girdi. Çanakkale Zaferi onun devrinde oldu. Ancak savaşın sonunda devlet ağır kayıplar verdi.",
    olaylar: ["Balkan Savaşları (1912-1913)", "I. Dünya Savaşı (1914-1918)", "Çanakkale Zaferi (1915)"],
    eserler: [],
    ilkler: ["Çanakkale Zaferi bu dönemde kazanıldı"],
    istatistik: { saltanatYil: 9, fetihler: 0 },
    baba: "abdulmecid",
    biliyorMuydun: "Mehmed Reşad döneminde Çanakkale'de 'Çanakkale geçilmez!' destanı yazılmıştır. 250.000 şehid vererek düşmanın geçmesi engellenmiştir."
  },
  {
    id: "mehmed-vahdeddin",
    sira: 36,
    ad: "Sultan Mehmed Vahdeddin",
    lakap: "Şehidler Yurdunu Düşmanın Elinden Kurtaran Fedakâr Sultan",
    saltanat: "1918–1922",
    donem: "dagilma",
    biyografi: "Osmanlı'nın son padişahıdır. Gençken fıkıh ilmini derinlemesine tahsil etti. Tahta çıktığında devlet, I. Dünya Savaşı'nın ağır yenilgileri ve işgallerle karşı karşıyaydı. İşgalcilere karşı Anadolu'daki direniş hareketlerini destekledi. Ancak İngiliz baskısı ve işgallerin ağırlığı altında kaldı. Hainlikle suçlandı ve sürgündeyken vefat etti.",
    olaylar: ["Mondros Mütarekesi (1918)", "İstanbul'un işgali (1920)", "Kurtuluş Savaşı", "Saltanatın kaldırılması (1922)"],
    eserler: [],
    ilkler: ["Osmanlı'nın son padişahı"],
    istatistik: { saltanatYil: 4, fetihler: 0 },
    baba: "abdulmecid",
    biliyorMuydun: "Vahdeddin, Mustafa Kemal'i Anadolu'ya gönderen padişahtır. Sürgünde San Remo'da vefat etmiş ve Şam'da defnedilmiştir."
  }
];

// ── QUIZ SORU HAVUZU ──────────────────────────────────────────
const SORULAR = [
  // Kolay
  { zorluk: 1, soru: "Osmanlı Devleti'nin kurucusu kimdir?", cevap: "Osman Gazi", siklar: ["Orhan Gazi", "Ertuğrul Gazi", "I. Murad"], sultanId: "osman-gazi" },
  { zorluk: 1, soru: "İstanbul'u fetheden padişah kimdir?", cevap: "Fatih Sultan Mehmed", siklar: ["Kanuni Sultan Süleyman", "Yavuz Sultan Selim", "II. Murad"], sultanId: "fatih-sultan-mehmed" },
  { zorluk: 1, soru: "İstanbul'un fetih yılı hangisidir?", cevap: "1453", siklar: ["1326", "1517", "1529"], sultanId: "fatih-sultan-mehmed" },
  { zorluk: 1, soru: "'Kanuni' lakabıyla bilinen padişah kimdir?", cevap: "Sultan Süleyman", siklar: ["Yavuz Selim", "Fatih Mehmed", "II. Bayezid"], sultanId: "kanuni-sultan-suleyman" },
  { zorluk: 1, soru: "Osmanlı'nın son padişahı kimdir?", cevap: "Mehmed Vahdeddin", siklar: ["Mehmed Reşad", "II. Abdülhamid", "Abdülmecid"], sultanId: "mehmed-vahdeddin" },
  { zorluk: 1, soru: "Sultanahmet Camii'ni yaptıran padişah kimdir?", cevap: "Sultan I. Ahmed", siklar: ["Kanuni Sultan Süleyman", "Fatih Sultan Mehmed", "Sultan III. Murad"], sultanId: "ahmed-1" },
  { zorluk: 1, soru: "'Yıldırım' lakaplı padişah kimdir?", cevap: "I. Bayezid", siklar: ["I. Murad", "Fatih Mehmed", "II. Mehmed"], sultanId: "bayezid-1" },
  { zorluk: 1, soru: "Hilafeti Osmanlı'ya taşıyan padişah kimdir?", cevap: "Yavuz Sultan Selim", siklar: ["Kanuni Sultan Süleyman", "Fatih Sultan Mehmed", "II. Bayezid"], sultanId: "yavuz-sultan-selim" },
  { zorluk: 1, soru: "Hicaz Demiryolu'nu yaptıran padişah kimdir?", cevap: "II. Abdülhamid", siklar: ["Abdülmecid", "Abdülaziz", "Mehmed Reşad"], sultanId: "abdulhamid-2" },
  { zorluk: 1, soru: "Osmanlı'nın ilk başkenti hangisidir?", cevap: "Bursa", siklar: ["Edirne", "İstanbul", "Söğüt"], sultanId: "orhan-gazi" },

  // Orta
  { zorluk: 2, soru: "Fetret Devri'ni sona erdiren padişah kimdir?", cevap: "Sultan I. Mehmed (Çelebi)", siklar: ["II. Murad", "I. Bayezid", "Orhan Gazi"], sultanId: "mehmed-1" },
  { zorluk: 2, soru: "Kosova Savaşı'nda şehid olan padişah kimdir?", cevap: "Sultan I. Murad", siklar: ["I. Bayezid", "Osman Gazi", "II. Murad"], sultanId: "murad-1" },
  { zorluk: 2, soru: "En uzun süre tahtta kalan padişah kimdir?", cevap: "Kanuni Sultan Süleyman (46 yıl)", siklar: ["II. Abdülhamid (33 yıl)", "IV. Mehmed (39 yıl)", "II. Bayezid (31 yıl)"], sultanId: "kanuni-sultan-suleyman" },
  { zorluk: 2, soru: "Yeniçeri Ocağı'nı kaldıran padişah kimdir?", cevap: "Sultan II. Mahmud", siklar: ["III. Selim", "Abdülmecid", "II. Abdülhamid"], sultanId: "mahmud-2" },
  { zorluk: 2, soru: "Lale Devri hangi padişah döneminde yaşanmıştır?", cevap: "Sultan III. Ahmed", siklar: ["I. Mahmud", "II. Mustafa", "III. Osman"], sultanId: "ahmed-3" },
  { zorluk: 2, soru: "Tanzimat Fermanı'nı ilan eden padişah kimdir?", cevap: "Sultan Abdülmecid", siklar: ["II. Mahmud", "Abdülaziz", "II. Abdülhamid"], sultanId: "abdulmecid" },
  { zorluk: 2, soru: "Nizam-ı Cedid ordusunu kuran padişah kimdir?", cevap: "Sultan III. Selim", siklar: ["II. Mahmud", "I. Abdülhamid", "Abdülmecid"], sultanId: "selim-3" },
  { zorluk: 2, soru: "'Çelebi' lakaplı padişah kimdir?", cevap: "Sultan I. Mehmed", siklar: ["II. Bayezid", "Orhan Gazi", "II. Murad"], sultanId: "mehmed-1" },
  { zorluk: 2, soru: "Karlofça Antlaşması hangi padişah döneminde imzalanmıştır?", cevap: "Sultan II. Mustafa", siklar: ["IV. Mehmed", "II. Ahmed", "III. Ahmed"], sultanId: "mustafa-2" },
  { zorluk: 2, soru: "Çaldıran Savaşı'nı kazanan padişah kimdir?", cevap: "Yavuz Sultan Selim", siklar: ["Kanuni Sultan Süleyman", "Fatih Sultan Mehmed", "II. Bayezid"], sultanId: "yavuz-sultan-selim" },
  { zorluk: 2, soru: "Edirne'yi fethederek başkent yapan padişah kimdir?", cevap: "Sultan I. Murad", siklar: ["Orhan Gazi", "I. Bayezid", "I. Mehmed"], sultanId: "murad-1" },
  { zorluk: 2, soru: "Avrupa'ya seyahat eden ilk Osmanlı padişahı kimdir?", cevap: "Sultan Abdülaziz", siklar: ["Abdülmecid", "II. Abdülhamid", "II. Mahmud"], sultanId: "abdulaziz" },
  { zorluk: 2, soru: "Dolmabahçe Sarayı'nı yaptıran padişah kimdir?", cevap: "Sultan Abdülmecid", siklar: ["Abdülaziz", "II. Mahmud", "II. Abdülhamid"], sultanId: "abdulmecid" },
  { zorluk: 2, soru: "Mohaç Savaşı hangi padişah döneminde olmuştur?", cevap: "Kanuni Sultan Süleyman", siklar: ["Yavuz Sultan Selim", "Fatih Sultan Mehmed", "II. Bayezid"], sultanId: "kanuni-sultan-suleyman" },
  { zorluk: 2, soru: "Şehzade katli geleneğini kaldıran padişah kimdir?", cevap: "Sultan I. Ahmed", siklar: ["III. Mehmed", "IV. Murad", "I. Mustafa"], sultanId: "ahmed-1" },

  // Zor
  { zorluk: 3, soru: "Osmanlı tarihinde ilk deniz savaşını yapan padişah kimdir?", cevap: "Sultan I. Mehmed (Çelebi)", siklar: ["Fatih Sultan Mehmed", "Orhan Gazi", "II. Bayezid"], sultanId: "mehmed-1" },
  { zorluk: 3, soru: "Ankara Savaşı'nda Timur'a esir düşen padişah kimdir?", cevap: "I. Bayezid (Yıldırım)", siklar: ["I. Mehmed", "II. Murad", "Osman Gazi"], sultanId: "bayezid-1" },
  { zorluk: 3, soru: "'Avcı Sultan' lakabıyla bilinen padişah kimdir?", cevap: "Sultan IV. Mehmed", siklar: ["IV. Murad", "II. Süleyman", "II. Ahmed"], sultanId: "mehmed-4" },
  { zorluk: 3, soru: "Selimiye Camii hangi padişah döneminde inşa edilmiştir?", cevap: "Sultan II. Selim", siklar: ["III. Murad", "Kanuni Sultan Süleyman", "II. Bayezid"], sultanId: "selim-2" },
  { zorluk: 3, soru: "İlk Osmanlı matbaası hangi padişah döneminde kurulmuştur?", cevap: "Sultan III. Ahmed (1727)", siklar: ["I. Mahmud", "II. Mahmud", "Abdülmecid"], sultanId: "ahmed-3" },
  { zorluk: 3, soru: "Haçova Meydan Savaşı hangi padişah döneminde kazanılmıştır?", cevap: "Sultan III. Mehmed", siklar: ["I. Ahmed", "III. Murad", "IV. Murad"], sultanId: "mehmed-3" },
  { zorluk: 3, soru: "Vaka-i Hayriye ne olayın adıdır?", cevap: "Yeniçeri Ocağı'nın kaldırılması", siklar: ["Tanzimat Fermanı", "Lale Devri", "II. Meşrutiyet"], sultanId: "mahmud-2" },
  { zorluk: 3, soru: "Bağdat Seferi'ni yapan ve şehri geri alan padişah kimdir?", cevap: "Sultan IV. Murad", siklar: ["Kanuni Sultan Süleyman", "Yavuz Sultan Selim", "III. Mehmed"], sultanId: "murad-4" },
  { zorluk: 3, soru: "Osmanlı padişahları arasında en çok şiir yazan padişah kimdir?", cevap: "Sultan III. Murad", siklar: ["I. Ahmed", "Fatih Sultan Mehmed", "Kanuni Sultan Süleyman"], sultanId: "murad-3" },
  { zorluk: 3, soru: "II. Viyana Kuşatması hangi padişah döneminde yapılmıştır?", cevap: "Sultan IV. Mehmed", siklar: ["Kanuni Sultan Süleyman", "IV. Murad", "II. Süleyman"], sultanId: "mehmed-4" },
  { zorluk: 3, soru: "Don-Volga kanalı projesini başlatan padişah kimdir?", cevap: "Sultan II. Selim", siklar: ["III. Murad", "Kanuni Sultan Süleyman", "I. Ahmed"], sultanId: "selim-2" },
  { zorluk: 3, soru: "Endülüs'ten Müslümanları Osmanlı topraklarına getiren padişah kimdir?", cevap: "Sultan II. Bayezid", siklar: ["Yavuz Sultan Selim", "Kanuni Sultan Süleyman", "Fatih Sultan Mehmed"], sultanId: "bayezid-2" },
  { zorluk: 3, soru: "Osmanlı'da ilk rasathane hangi padişah döneminde yapılmıştır?", cevap: "Sultan III. Murad", siklar: ["III. Mustafa", "Kanuni Sultan Süleyman", "I. Mahmud"], sultanId: "murad-3" },
  { zorluk: 3, soru: "'Genç Osman' olarak bilinen ve darbe ile şehid edilen padişah kimdir?", cevap: "Sultan II. Osman", siklar: ["IV. Murad", "Sultan İbrahim", "I. Mustafa"], sultanId: "osman-2" },
  { zorluk: 3, soru: "Girit'in fethi hangi padişah döneminde tamamlanmıştır?", cevap: "Sultan IV. Mehmed", siklar: ["Sultan İbrahim", "II. Süleyman", "III. Mehmed"], sultanId: "mehmed-4" },

  // Doğru/Yanlış
  { zorluk: 1, soru: "İstanbul 1453 yılında fethedilmiştir.", cevap: "Doğru", siklar: ["Yanlış"], tip: "dogruYanlis" },
  { zorluk: 1, soru: "Osmanlı'nın ilk başkenti Edirne'dir.", cevap: "Yanlış", siklar: ["Doğru"], tip: "dogruYanlis" },
  { zorluk: 2, soru: "Yeniçeri Ocağı'nı II. Mahmud kaldırmıştır.", cevap: "Doğru", siklar: ["Yanlış"], tip: "dogruYanlis" },
  { zorluk: 2, soru: "Fatih Sultan Mehmed 5 dil biliyordu.", cevap: "Yanlış", siklar: ["Doğru"], tip: "dogruYanlis" },
  { zorluk: 2, soru: "Lale Devri, III. Ahmed döneminde yaşanmıştır.", cevap: "Doğru", siklar: ["Yanlış"], tip: "dogruYanlis" },
  { zorluk: 3, soru: "Osmanlı tarihinin ilk deniz savaşı I. Mehmed döneminde yapılmıştır.", cevap: "Doğru", siklar: ["Yanlış"], tip: "dogruYanlis" },
  { zorluk: 3, soru: "Kanuni Sultan Süleyman 'Avni' mahlasıyla şiir yazmıştır.", cevap: "Yanlış", siklar: ["Doğru"], tip: "dogruYanlis" },
  { zorluk: 3, soru: "Karlofça Antlaşması 1699 yılında imzalanmıştır.", cevap: "Doğru", siklar: ["Yanlış"], tip: "dogruYanlis" },
];

// ── ROZET TANIMLARI ───────────────────────────────────────────
const ROZETLER = [
  { id: "ilk-adim",     ad: "İlk Adım",           ikon: "🏰", kosul: "İlk quiz'i tamamla", puan: 50 },
  { id: "kurulus-uzmani",ad: "Kuruluş Uzmanı",     ikon: "🌱", kosul: "Kuruluş dönemi quiz'ini %100 tamamla", puan: 200 },
  { id: "yukselis-uzmani",ad:"Yükseliş Uzmanı",    ikon: "⚔️", kosul: "Yükseliş dönemi quiz'ini %100 tamamla", puan: 200 },
  { id: "duraklama-uzmani",ad:"Duraklama Uzmanı",  ikon: "⚖️", kosul: "Duraklama dönemi quiz'ini %100 tamamla", puan: 200 },
  { id: "gerileme-uzmani",ad:"Gerileme Uzmanı",    ikon: "📉", kosul: "Gerileme dönemi quiz'ini %100 tamamla", puan: 200 },
  { id: "dagilma-uzmani", ad:"Dağılma Uzmanı",     ikon: "🏚️", kosul: "Dağılma dönemi quiz'ini %100 tamamla", puan: 200 },
  { id: "fatih-izinde",  ad: "Fatih'in İzinde",    ikon: "🗡️", kosul: "İstanbul Fethi sorularını hepsini bil", puan: 300 },
  { id: "kronoloji-ustasi",ad:"Kronoloji Ustası",  ikon: "⏳", kosul: "36 sultanı 90 saniyede sırala", puan: 500 },
  { id: "hafiza-sampiyon",ad:"Hafıza Şampiyonu",   ikon: "🧠", kosul: "Eşleştirme oyununu 60 saniyede tamamla", puan: 300 },
  { id: "quiz-ustasi",   ad: "Quiz Ustası",        ikon: "🎯", kosul: "50 quiz sorusu doğru cevapla", puan: 200 },
  { id: "bilgi-makinesi",ad: "Bilgi Makinesi",     ikon: "⚡", kosul: "Hızlı turda 20+ doğru yap", puan: 300 },
  { id: "koleksiyoncu",  ad: "Koleksiyoncu",       ikon: "📚", kosul: "Tüm 36 kartı topla", puan: 500 },
  { id: "jeopardy-yildizi",ad:"Jeopardy Yıldızı", ikon: "⭐", kosul: "Jeopardy'de 2000+ puan yap", puan: 400 },
  { id: "arena-sampiyon", ad:"Arena Şampiyonu",     ikon: "🏆", kosul: "Sultan Arenası'nda 10 maç kazan", puan: 300 },
  { id: "gunluk-calisan", ad:"Günlük Çalışkan",    ikon: "📅", kosul: "3 gün üst üste gir", puan: 100 },
  { id: "dedektif",      ad: "Dedektif",            ikon: "🔍", kosul: "'Kim Bu Sultan?'da ilk ipucunda bil", puan: 400 },
  { id: "tam-isabet",    ad: "Tam İsabet",          ikon: "💯", kosul: "Bir quiz'de hiç hata yapma", puan: 200 },
  { id: "tarih-gurusu",  ad: "Tarih Gurusu",       ikon: "🎓", kosul: "Zor seviye quiz'de %90+ yap", puan: 500 },
  { id: "sultan-seviye", ad: "Sultan Seviyesi",     ikon: "👑", kosul: "Sultan seviyesine ulaş (5000 XP)", puan: 1000 },
];

// ── SEVİYE SİSTEMİ ──────────────────────────────────────────
const SEVIYELER = [
  { ad: "Yeniçeri",   ikon: "🏹", minXP: 0 },
  { ad: "Sipahi",     ikon: "🐎", minXP: 200 },
  { ad: "Paşa",       ikon: "⚔️", minXP: 500 },
  { ad: "Vezir",      ikon: "📜", minXP: 1000 },
  { ad: "Sadrazam",   ikon: "🏛️", minXP: 2000 },
  { ad: "Sultan",     ikon: "👑", minXP: 5000 },
];

// ── JEOPARDY KATEGORİLERİ ──────────────────────────────────
const JEOPARDY_KATEGORILER = [
  {
    ad: "Savaşlar",
    sorular: [
      { puan: 100, soru: "1453'te İstanbul'u fetheden padişah?", cevap: "Fatih Sultan Mehmed" },
      { puan: 200, soru: "Niğbolu Savaşı'nı kazanan padişah?", cevap: "I. Bayezid (Yıldırım)" },
      { puan: 300, soru: "Çaldıran Savaşı hangi yılda olmuştur?", cevap: "1514" },
      { puan: 400, soru: "Haçova Meydan Savaşı'nı kazanan padişah?", cevap: "III. Mehmed" },
      { puan: 500, soru: "Zenta Muharebesi'nin kaybıyla hangi antlaşma imzalanmıştır?", cevap: "Karlofça Antlaşması (1699)" },
    ]
  },
  {
    ad: "Eserler",
    sorular: [
      { puan: 100, soru: "Sultanahmet Camii'ni yaptıran padişah?", cevap: "I. Ahmed" },
      { puan: 200, soru: "Süleymaniye Külliyesi'ni yaptıran padişah?", cevap: "Kanuni Sultan Süleyman" },
      { puan: 300, soru: "Dolmabahçe Sarayı'nı yaptıran padişah?", cevap: "Abdülmecid" },
      { puan: 400, soru: "Selimiye Camii hangi padişah döneminde inşa edilmiştir?", cevap: "II. Selim" },
      { puan: 500, soru: "Anadolu Hisarı'nı yaptıran padişah?", cevap: "I. Bayezid (Yıldırım)" },
    ]
  },
  {
    ad: "İlkler",
    sorular: [
      { puan: 100, soru: "'Sultan' unvanını kullanan ilk padişah?", cevap: "I. Murad" },
      { puan: 200, soru: "Avrupa'ya seyahat eden ilk padişah?", cevap: "Abdülaziz" },
      { puan: 300, soru: "Osmanlı'da ilk matbaanın kurulduğu dönem?", cevap: "III. Ahmed - Lale Devri (1727)" },
      { puan: 400, soru: "Tahtı kendi isteğiyle bırakan ilk padişah?", cevap: "II. Murad" },
      { puan: 500, soru: "İlk Osmanlı deniz savaşını yapan padişah?", cevap: "I. Mehmed (Çelebi)" },
    ]
  },
  {
    ad: "Islahatlar",
    sorular: [
      { puan: 100, soru: "Tanzimat Fermanı'nı ilan eden padişah?", cevap: "Abdülmecid" },
      { puan: 200, soru: "Nizam-ı Cedid ordusunu kuran padişah?", cevap: "III. Selim" },
      { puan: 300, soru: "Vaka-i Hayriye nedir?", cevap: "Yeniçeri Ocağı'nın kaldırılması (1826)" },
      { puan: 400, soru: "Hicaz Demiryolu'nu yaptıran padişah?", cevap: "II. Abdülhamid" },
      { puan: 500, soru: "Humbaracı Ahmet Paşa ıslahatları hangi dönemde?", cevap: "I. Mahmud dönemi" },
    ]
  },
  {
    ad: "Lakaplar",
    sorular: [
      { puan: 100, soru: "'Fatih' lakaplı padişah?", cevap: "Sultan II. Mehmed" },
      { puan: 200, soru: "'Kanuni' lakaplı padişah?", cevap: "Sultan Süleyman" },
      { puan: 300, soru: "'Ulu Hakan' lakaplı padişah?", cevap: "II. Abdülhamid" },
      { puan: 400, soru: "'Hüdavendigâr' lakaplı padişah?", cevap: "I. Murad" },
      { puan: 500, soru: "'Bayezid-i Veli' lakaplı padişah?", cevap: "II. Bayezid" },
    ]
  },
];

// ── DÜNYA OLAYLARI (Timeline için) ──────────────────────────
const DUNYA_OLAYLARI = [
  { yil: 1299, olay: "Osmanlı Beyliği kuruldu" },
  { yil: 1347, olay: "Kara Veba Avrupa'yı sardı" },
  { yil: 1453, olay: "İstanbul'un Fethi / Ortaçağ sona erdi" },
  { yil: 1492, olay: "Kolomb Amerika'yı keşfetti" },
  { yil: 1517, olay: "Martin Luther'in 95 Tezi / Reform başladı" },
  { yil: 1543, olay: "Kopernik güneş merkezli modeli yayınladı" },
  { yil: 1588, olay: "İspanyol Armadası yenildi" },
  { yil: 1687, olay: "Newton yerçekimi kanununu yayınladı" },
  { yil: 1776, olay: "ABD bağımsızlık ilanı" },
  { yil: 1789, olay: "Fransız Devrimi" },
  { yil: 1804, olay: "Napolyon imparator oldu" },
  { yil: 1869, olay: "Süveyş Kanalı açıldı" },
  { yil: 1914, olay: "I. Dünya Savaşı başladı" },
  { yil: 1922, olay: "Osmanlı Saltanatı kaldırıldı" },
];
