// İslam Alimleri Kart Seti — Veri Dosyası
// 22 büyük İslam alimi, quiz soruları ve rozet tanımları

const ALANLAR = {
  hadis:    { ad: "Hadis İlmi",        renk: "#22c55e", ikon: "📖", yy: "II–III. yy" },
  fikih:    { ad: "Fıkıh / Usul",      renk: "#f59e0b", ikon: "⚖️", yy: "II–X. yy"  },
  tefsir:   { ad: "Tefsir / Kur'an",   renk: "#3b82f6", ikon: "📕", yy: "II–V. yy"  },
  kelam:    { ad: "Kelam / Akaid",     renk: "#8b5cf6", ikon: "🔮", yy: "III–VII. yy"},
  tasavvuf: { ad: "Tasavvuf",          renk: "#ec4899", ikon: "🌸", yy: "II–XIII. yy"},
  bilim:    { ad: "Bilim / Felsefe",   renk: "#06b6d4", ikon: "🔭", yy: "IV–IX. yy" },
  tarih:    { ad: "Tarih / Coğrafya",  renk: "#ef4444", ikon: "🗺️", yy: "III–VIII. yy"}
};

const ALIMLER = [
  {
    id: "ebu-hanife",
    sira: 1,
    ad: "İmâm-ı Âzam Ebû Hanîfe",
    lakap: "İmâm-ı Âzam — En Büyük İmam",
    yasadi: "699–767",
    dogum: "Kûfe",
    alan: "fikih",
    biyografi: "Numan b. Sabit olarak bilinen Ebû Hanîfe, kendi adıyla anılan Hanefi mezhebinin kurucusudur. Ticaretle uğraşırken Hammad b. Ebî Süleyman'ın derslerine katılmış ve zamanla İslam hukukunun en büyük sistemcisi hâline gelmiştir. Rey ve kıyas yöntemini geliştirerek fıkhı akıl ve nas dengesiyle temellendirmiştir.",
    eserler: ["el-Fıkhu'l-Ekber", "el-Âlim ve'l-Müteallim", "el-Vasiyye"],
    onemliOlaylar: ["18 yıl Hammad'ın yanında tahsil", "Abbasi hapishanesi — yargılanması", "Ölümünden yüzyıllar sonra Bağdat'ta türbesi ziyaretgâh oldu"],
    katki: "Hanefi fıkhının kurucusu; kıyas ve istihsan metodolojisini sistemleştirdi",
    biliyorMuydun: "Hayatı boyunca iki kez kadılık teklifini reddetti. 'Kadılık görevi cehennem kapılarından biridir' derdi. Bu ret yüzünden hapse atıldı."
  },
  {
    id: "imam-malik",
    sira: 2,
    ad: "İmam Mâlik b. Enes",
    lakap: "İmâmu Dâri'l-Hicre — Medine'nin İmamı",
    yasadi: "711–795",
    dogum: "Medine",
    alan: "hadis",
    biyografi: "Hadis ilminin en büyük otoritelerinden biri ve Maliki mezhebinin kurucusudur. Ömrü boyunca Medine'den ayrılmamış, Hz. Peygamber'in şehrini ilim merkezi olarak gördüğünden Medine uygulamasını (amelu ehli'l-Medine) hadisle eşdeğer saymıştır.",
    eserler: ["el-Muvatta — ilk sistematik hadis-fıkıh eseri"],
    onemliOlaylar: ["Talak meselesinde Abbasi valisi tarafından dövdürüldü", "Halife Hârun Reşid ile görüşmesi", "İmam Şafi'nin ondan ders alması"],
    katki: "el-Muvatta ile hadis-fıkıh sentezini kurdu; Maliki mezhebi Kuzey Afrika ve Endülüs'e yayıldı",
    biliyorMuydun: "el-Muvatta'yı yazmadan önce 70 fakihle istişare etmiş ve onların onayını almıştır. Kâbe'ye girdiğinde bile kitabı yanından ayırmamıştır."
  },
  {
    id: "imam-safi",
    sira: 3,
    ad: "İmam Muhammed b. İdrîs eş-Şâfiî",
    lakap: "Nâsıru's-Sünne — Sünnetin Yardımcısı",
    yasadi: "767–820",
    dogum: "Gazze (Filistin)",
    alan: "fikih",
    biyografi: "Hz. Peygamber'in Kureyş soyundan gelen Şâfiî, hem Malik'ten hem İmam Muhammed'den ders alarak iki büyük ekolü sentezledi. Usûlü'l-fıkh ilminin kurucusu sayılır; er-Risâle adlı eseriyle İslam hukuk metodolojisini ilk kez sistematik biçimde ele aldı.",
    eserler: ["er-Risâle — ilk usûl-i fıkıh eseri", "el-Ümm — fıkıh ansiklopedisi"],
    onemliOlaylar: ["Bağdat'ta 'Kadim görüş', Mısır'da 'Yeni görüş' geliştirdi", "İmam Ahmed b. Hanbel ona 'benim gibi olanlar için namaz kılıyorum' dedi"],
    katki: "Fıkıh usulünü bilim olarak kurdu; dört mezhep içinde en geniş coğrafyaya yayılanı",
    biliyorMuydun: "İki mezhep kurucudan (Malik ve Şeybani) ders aldı, bu sayede iki farklı ekolü sentezledi. Arapçayı o kadar iyi bilirdi ki şiiriyle dil alimleri bile hayranlık duyardı."
  },
  {
    id: "ahmed-ibn-hanbel",
    sira: 4,
    ad: "İmam Ahmed b. Hanbel",
    lakap: "İmâmu's-Sünne — Sünnetin İmamı",
    yasadi: "780–855",
    dogum: "Bağdat",
    alan: "hadis",
    biyografi: "Hanbeli mezhebinin kurucusu ve Mihne döneminin kahraman şahsiyeti. Halife Me'mun'un Kur'an'ın mahlûk olduğu görüşünü kabul etmesini dayatmasına karşı çıkarak yıllarca hapsedildi ve işkenceye maruz kaldı; ama görüşünden asla vazgeçmedi.",
    eserler: ["el-Müsned — 30.000 hadis içeren dev koleksiyon", "es-Sünne", "el-Verra"],
    onemliOlaylar: ["Mihne döneminde kırbaçlanma ve hapis", "Bağdat'taki cenaze törenine 800.000 kişi katıldı (rivayete göre)"],
    katki: "Hadis ehlinin sembolü; Mihne'ye direnciyle akaidin temel prensiplerini savundu",
    biliyorMuydun: "Yüz binlerce hadis ezberlediği söylenir. İmam Şafi hakkında 'Fıkıhta ona muhtaçtım, o benden hadis öğrendi' demiştir."
  },
  {
    id: "imam-buhari",
    sira: 5,
    ad: "İmam Muhammed b. İsmâîl el-Buhârî",
    lakap: "Emîru'l-Mü'minîn fi'l-Hadîs — Hadis'in Emiri",
    yasadi: "810–870",
    dogum: "Buhara (Özbekistan)",
    alan: "hadis",
    biyografi: "Hadis ilminin zirvesi sayılan el-Câmiu's-Sahîh'in müellifi. 600.000 hadis arasından seçtiği 7.275 sahih hadisi eserine aldı. Her hadisi yazmadan önce gusül abdesti alıp iki rekât namaz kılar, o hadisin doğruluğuna kanaat getirdikten sonra yazardı.",
    eserler: ["el-Câmiu's-Sahîh (Sahîh-i Buhârî)", "et-Târîhu'l-Kebîr", "el-Edebü'l-Müfred"],
    onemliOlaylar: ["16 yıl hadis seyahati", "600.000 hadis inceledi, 7275'ini sahih kabul etti", "Semerkand'a sürgün, orada vefat etti"],
    katki: "Kur'an'dan sonra en güvenilir kitap olarak kabul edilen Sahih-i Buhari'yi derledi",
    biliyorMuydun: "10 yaşında hadis ezberlemeve başladı. Bağdat'a geldiğinde muhaddisler onu sınamak için 100 karıştırılmış hadis okudular; hepsini doğru tanımlayıp düzeltti."
  },
  {
    id: "imam-muslim",
    sira: 6,
    ad: "İmam Müslim b. Haccâc",
    lakap: "el-Hafız — Büyük Hafız",
    yasadi: "815–875",
    dogum: "Nişabur (İran)",
    alan: "hadis",
    biyografi: "Sahih-i Müslim'in müellifi. Buhari ile çağdaş olan Müslim, özellikle sened (rivayet zinciri) tenkit metodolojisinde çığır açtı. Hadislerini konulara göre sistematik bir şekilde düzenleyerek ilk tematik hadis koleksiyonunu oluşturdu.",
    eserler: ["el-Câmiu's-Sahîh (Sahîh-i Müslim)", "el-Müsned el-Kebîr", "el-Künâ ve'l-Esmâ"],
    onemliOlaylar: ["Buhari ile birlikte Yahya b. Maîn'den ders aldı", "300.000 hadis inceledi, 9200'ünü sahih kabul etti"],
    katki: "Kütüb-ü Sitte'nin ikinci kitabı Sahih-i Müslim; hadis sıhhat metodolojisini geliştirdi",
    biliyorMuydun: "İmam Buhari ile Nişabur'da karşılaştıklarında Müslim ona saygısından ayağa kalktı ve 'Sana benden babadan fazla saygı duyuyorum' dedi."
  },
  {
    id: "imam-buhari-taberi",
    sira: 7,
    ad: "İmam Muhammed b. Cerîr et-Taberî",
    lakap: "İmâmu'l-Müfessirîn — Tefsir İmamı",
    yasadi: "839–923",
    dogum: "Âmül, Taberistan (İran)",
    alan: "tefsir",
    biyografi: "İslam tarihinin en büyük tefsir ve tarih âlimlerinden biri. Câmiu'l-beyân adlı tefsiri 30 cilt halinde Kur'an'ın tamamını ele alır. Tarih alanında ise Tarihu'r-Rusul ve'l-Mulûk adlı eseriyle evrensel tarih yazıcılığının öncüsü oldu.",
    eserler: ["Câmiu'l-Beyân fî Tefsîri'l-Kur'ân (30 cilt)", "Tarihu'l-Ümem ve'l-Mülûk (10 cilt)"],
    onemliOlaylar: ["Her gün 40 varak yazdığı söylenir", "Bağdat'ta 40 yıl ders verdi", "Ölümünden sonra halk tarafından defnine izin verilmedi (siyasi nedenlerle)"],
    katki: "Kur'an tefsirinde selef görüşlerini en kapsamlı biçimde toplayan rivayet tefsiri; İslam tarih yazımının kurucusu",
    biliyorMuydun: "Gençliğinde İmam Ahmed b. Hanbel'den ders almak için Bağdat'a geldi; ancak İmam vefat etmişti. Üzüntüsünü ancak eserlerine çalışarak kapattı."
  },
  {
    id: "ibn-sina",
    sira: 8,
    ad: "İbn Sînâ — Ebû Alî el-Hüseyn",
    lakap: "eş-Şeyhu'r-Reîs — Filozofların Önderi",
    yasadi: "980–1037",
    dogum: "Buhara yakını Afşene (Özbekistan)",
    alan: "bilim",
    biyografi: "Tıp, felsefe, astronomi ve müzik dahil yüzlerce alanda eser veren İbn Sina, Orta Çağ'ın en etkili bilim insanıdır. el-Kânûn fi't-Tıb adlı eseri 600 yıl boyunca Avrupa üniversitelerinde ders kitabı olarak okutuldu.",
    eserler: ["el-Kânûn fi't-Tıb", "Kitâbu'ş-Şifâ (18 cilt)", "Risâle fi'l-Aşk"],
    onemliOlaylar: ["10 yaşında Kur'an'ı ezberledi", "18 yaşında tam doktor", "Çeşitli hükümdarlara vezirlik yaptı", "Hayatı boyunca siyasi baskılardan kaçarak sürekli şehir değiştirdi"],
    katki: "Modern anatominin, farmakolojinin ve klinik tıbbın öncüsü; Batı'da 'Avicenna' adıyla tanındı",
    biliyorMuydun: "el-Kânûn'da alkol bağımlılığını tedavi eden protokoller, karantina kurallarını ve bulaşıcı hastalıkları hava yoluyla yayılabileceğini açıkladı — bundan 800 yıl önce."
  },
  {
    id: "el-biruni",
    sira: 9,
    ad: "Ebû Reyhan Muhammed el-Bîrûnî",
    lakap: "el-Üstâz — Üstat",
    yasadi: "973–1048",
    dogum: "Harezm (Türkmenistan/Özbekistan)",
    alan: "bilim",
    biyografi: "Matematik, astronomi, fizik, mineroloji, tarih, coğrafya ve Hint bilimleri alanında çığır açan Bîrûnî, dünyanın ilk polimatlanndan biridir. Hint kıtasını bizzat gezerek Hint bilimini Arapçaya aktardı. Yerçekimini ve Dünya'nın yaşını hesaplamaya çalıştı.",
    eserler: ["el-Kânûn el-Mes'ûdî", "Tahkîku mâ li'l-Hind", "el-Âsâru'l-Bâkıye"],
    onemliOlaylar: ["Gazneli Mahmud'un sarayında 13 yıl", "Hint'e giderek Sanskritçe öğrendi", "Yerin çevresini çok doğru hesapladı"],
    katki: "Karşılaştırmalı din araştırmalarının kurucusu; Hint bilimini Arap/İslam dünyasına tanıttı",
    biliyorMuydun: "Amerika kıtasının keşfinden 400 yıl önce, hesaplamaları yaparak Atlas Okyanusu'nun karşısında bilinmeyen bir kıtanın olabileceğini öngördü."
  },
  {
    id: "imam-gazali",
    sira: 10,
    ad: "İmam Ebû Hâmid Muhammed el-Gazzâlî",
    lakap: "Hüccetu'l-İslâm — İslam'ın Delili",
    yasadi: "1058–1111",
    dogum: "Tus (İran)",
    alan: "kelam",
    biyografi: "İslam düşünce tarihinin en etkili ismi olan Gazzâlî, Bağdat Nizamiye Medresesi'nde müderrislik yaparken ani bir ruhani bunalıma girdi ve her şeyi bırakıp 10 yıl tasavvuf yolculuğuna çıktı. Bu deneyimini İhyâu Ulûmi'd-Dîn adlı şaheserinde aktardı.",
    eserler: ["İhyâu Ulûmi'd-Dîn (4 cilt)", "Tehâfütü'l-Felâsife", "el-Munkız mine'd-Dalâl", "Mişkâtu'l-Envâr"],
    onemliOlaylar: ["33 yaşında Bağdat'ın en büyük âlimi", "Ani dönüşüm — 10 yıl inziva", "Felsefecilere karşı Tehafüt'ü yazdı"],
    katki: "Kelam, felsefe ve tasavvufu sentezledi; İslam ahlak felsefesinin zirvesi İhya'yı yazdı",
    biliyorMuydun: "Batı'da Descartesçı şüpheciliğe benzer yöntemi, Descartes'tan 500 yıl önce el-Munkız'da uyguladı. Kendi bilgisini köklü biçimde sorguladı."
  },
  {
    id: "ibn-rüsd",
    sira: 11,
    ad: "İbn Rüşd — Ebû'l-Velîd Muhammed",
    lakap: "el-Feylesûf — Filozof",
    yasadi: "1126–1198",
    dogum: "Kurtuba/Kordoba (Endülüs)",
    alan: "bilim",
    biyografi: "Aristoteles'in tüm eserlerini şerh ederek Orta Çağ Avrupası'na ulaştıran İbn Rüşd, Batı'da 'Averroes' adıyla tanındı. Gazzâlî'nin felsefe eleştirilerine Tehâfütü't-Tehâfüt adlı eseriyle yanıt verdi. Kadılık ve hekimliği bir arada yürüttü.",
    eserler: ["Tehâfütü't-Tehâfüt", "Bidâyetü'l-Müctehid (Fıkıh)", "Kitâbu'l-Külliyyât (Tıp)"],
    onemliOlaylar: ["Endülüs'te büyük saygınlık kazandı", "Yaşlılığında Halife tarafından sürgün edildi", "Eserleri Avrupa Ortaçağ düşüncesini derinden etkiledi"],
    katki: "Aristoteles'in İslam ve Batı'ya aktarılmasında kilit figür; rasyonel akıl savunucusu",
    biliyorMuydun: "Batı'da 'Commentator' (Şârihin Ta Kendisi) olarak anıldı. Dante, İlahi Komedya'da İbn Rüşd'e Cehennem'de değil, Limbo'da — filozoflar arasında — yer verdi."
  },
  {
    id: "ibn-arabi",
    sira: 12,
    ad: "Muhyiddin İbn Arabî",
    lakap: "eş-Şeyhu'l-Ekber — En Büyük Şeyh",
    yasadi: "1165–1240",
    dogum: "Mürsiye (Endülüs)",
    alan: "tasavvuf",
    biyografi: "İslam tasavvuf düşüncesinin en karmaşık ve en tartışmalı ismi. Vahdet-i Vücud (Varlığın Birliği) nazariyesini sistematik biçimde geliştirdi. Ömrünün son yıllarını Şam'da geçirdi; bugün türbesi orada ziyaret edilmektedir.",
    eserler: ["el-Fütûhâtu'l-Mekkiyye (37 cilt)", "Fusûsu'l-Hikem", "Tercümânu'l-Eşvâk"],
    onemliOlaylar: ["Mekke'de ruhani açılım yaşadı", "Endülüs'ten Bağdat'a, oradan Şam'a uzun yolculuk", "Ölümünden sonra hem derin saygı hem sert eleştiri aldı"],
    katki: "Tasavvuf felsefesini en üst sisteme taşıdı; Osmanlı, Fars ve Hint tasavvufunu derinden etkiledi",
    biliyorMuydun: "el-Fütûhât, Mekke'de Kâbe'yi tavaf ederken içine doğan ilhamlarla yazılmıştır — yıllar içinde 37 cilde ulaştı."
  },
  {
    id: "mevlana",
    sira: 13,
    ad: "Mevlânâ Celâleddin Muhammed Rûmî",
    lakap: "Mevlânâ — Efendimiz",
    yasadi: "1207–1273",
    dogum: "Belh (Afganistan)",
    alan: "tasavvuf",
    biyografi: "Tarihte en çok okunan şairlerden olan Mevlana, Moğol istilasından kaçarak Anadolu'ya sığınan ailesinin çocuğudur. Şems-i Tebrîzî ile karşılaşması hayatını kökten değiştirdi. Konya'yı ilim, aşk ve hoşgörü merkezi hâline getirdi; Mesnevi'si 25.000'den fazla beyit içerir.",
    eserler: ["Mesnevi (6 cilt, 25.618 beyit)", "Divân-ı Kebîr", "Fîhi Mâ Fîh"],
    onemliOlaylar: ["Şems-i Tebrîzî ile buluşma (1244)", "Şems'in kaybolması ve yas dönemi", "Sema ritüelinin ruhanî merkezi olması"],
    katki: "İslam tasavvufunun en lirik sesi; Mevlevî tarikatının kurucusu; dünya edebiyatının zirvesi",
    biliyorMuydun: "Mesnevi'nin ilk 18 beytini (neyin feryadı) 'canın bedenden ayrılışının ağıdı' olarak nitelendirdi. Bu beyitler 750 yıldır dünyanın her köşesinde okunmaktadır."
  },
  {
    id: "ibn-teymiyye",
    sira: 14,
    ad: "Takiyyüddin Ahmed İbn Teymiyye",
    lakap: "Şeyhu'l-İslâm — İslam Şeyhi",
    yasadi: "1263–1328",
    dogum: "Harran (Türkiye/Suriye sınırı)",
    alan: "kelam",
    biyografi: "Moğol istilasından kaçarak Şam'a yerleşen ailesiyle birlikte büyüdü. Dini reformcu kişiliği ve naslara bağlılığıyla hem etkili hem tartışmalı bir figür oldu. Ömrünün büyük bölümünü Şam ve Kahire'nin çeşitli hapishanelerinde geçirdi.",
    eserler: ["Mecmûu'l-Fetâvâ (37 cilt)", "Minhâcu's-Sünne", "Der'ü Teârudi'l-Akl ve'n-Nakl"],
    onemliOlaylar: ["Moğollara karşı cihat fetvası", "Defalarca hapsedildi", "Son hapsinde kitap ve kalem elinden alındı, parmaklarıyla taş üzerine yazdı"],
    katki: "Selefi hareketlerin öncüsü; bid'at eleştirisi ve naslara dönüş çağrısı",
    biliyorMuydun: "Son hapis döneminde kitap ve kalem yasaklandığında, parmağıyla tuz taşı üzerine yazarak ilim üretmeyi sürdürdü. Hapishanede vefat etti."
  },
  {
    id: "ibn-haldun",
    sira: 15,
    ad: "Abdurrahman İbn Haldûn",
    lakap: "Ebü'z-Zamân — Çağın Babası",
    yasadi: "1332–1406",
    dogum: "Tunus",
    alan: "tarih",
    biyografi: "Sosyoloji, tarih felsefesi ve ekonomi bilimlerinin öncüsü sayılan İbn Haldun, Kuzey Afrika ve Endülüs'ün çalkantılı siyasi ortamında büyüdü. Mukaddime adlı eseriyle medeniyet yükseliş ve çöküşünü asabiyye kuramıyla açıkladı.",
    eserler: ["Mukaddime — tarih ve sosyoloji şaheseri", "el-İber (7 cilt tarih)"],
    onemliOlaylar: ["Mağrip'te çeşitli hükümdarlara vezirlik", "Kahire'de yargıç olarak görev", "Timurlenk ile tarihi buluşma (1401)"],
    katki: "Modern sosyoloji, tarih felsefesi ve siyaset biliminin kurucusu; asabiyye teorisi",
    biliyorMuydun: "Timurlenk Şam'ı kuşattığında şehrin kapısından ip ile sarkıtılarak dışarı çıktı ve Timurlenk ile bizzat müzakere etti. Bu görüşmeyi kendi Mukaddime haşiyesine not etti."
  },
  {
    id: "haci-bayram-veli",
    sira: 16,
    ad: "Hacı Bayrâm-ı Velî",
    lakap: "Sultânu'l-Ârifîn — Arifler Sultanı",
    yasadi: "1352–1430",
    dogum: "Ankara",
    alan: "tasavvuf",
    biyografi: "Bayramiyye tarikatının kurucusu. Ankara'ya yakın Solfasol köyünde doğan Numan (asıl adı), Ankara yakınlarındaki Karacadağ'da mürşidi Hamîdüddîn Aksarâyî ile tanışarak tasavvuf yoluna girdi. Bayram namazı gününde biat ettiği için 'Bayram' lakabı aldı.",
    eserler: ["Divan (Türkçe ve Arapça şiirler)"],
    onemliOlaylar: ["Çelebi Mehmed ile görüşmesi", "II. Murad onu Edirne'ye çağırdı, vergisini bağışladı", "Fatih Sultan Mehmed'e hocalık eden Akşemseddin ona intisap etti"],
    katki: "Anadolu'da Türkçe tasavvuf şiirinin öncüsü; Bayramiyye tarikatının kurucusu",
    biliyorMuydun: "Rivayete göre şehrin ne zaman fethedilebileceği sorulduğunda müridi Akşemseddin'e işaret etmiştir. Konstantinopolis'in fethini göremeden vefat etmiş, ancak manevi müjdeyi bırakmıştır."
  },
  {
    id: "aksemsettin",
    sira: 17,
    ad: "Akşemseddin Mehmed b. Hamza",
    lakap: "Kutbu'l-Ârifîn — Ariflerin Kutbu",
    yasadi: "1389–1459",
    dogum: "Şam (Suriye)",
    alan: "tasavvuf",
    biyografi: "Fatih Sultan Mehmed'in hocası ve manevi rehberi. Tıp ve botanik alanında da ileri gelen Akşemseddin, İstanbul'un fethinden önce Hz. Ebu Eyyüb el-Ensari'nin kabrini keşfetmesiyle meşhur olmuştur. Gerede'ye yakın Göynük'te vefat etmiştir.",
    eserler: ["Mâddetü'l-Hayât", "Risâle-i Zikrullah", "Def-i Metâin"],
    onemliOlaylar: ["Hz. Eyyüb el-Ensari'nin kabrini bulması", "Fetih sırasında orduya manevi önderlik", "Mâddetü'l-Hayât'ta mikrop teorisini önceden işaret etti"],
    katki: "İstanbul'un manevi fatihi; tıbbî eserleriyle bulaşıcı hastalık teorisini önceden sezdi",
    biliyorMuydun: "Mâddetü'l-Hayât'ta 'Hastalıklar gözle görülemeyen canlılardan (madde-i hayât) kaynaklanır' yazdı — bu, Pasteur'dan 400 yıl önceydi."
  },
  {
    id: "ali-kuscu",
    sira: 18,
    ad: "Ali Kuşçu — Alâeddin Ali b. Muhammed",
    lakap: "Muhakkikîn-i Felek — Gökyüzünün Hakikati",
    yasadi: "1403–1474",
    dogum: "Semerkand (Özbekistan)",
    alan: "bilim",
    biyografi: "Uluğ Bey'in en seçkin talebesi ve Osmanlı astronomi medreselerinin kurucusu. Semerkand'dan İstanbul'a uzun yolculuğu esnasında her konak yerinde bir bilimsel risâle kaleme alarak Fatih Sultan Mehmed'e sundu. Ayasofya medresesinde astronomi dersleri verdi.",
    eserler: ["Risâle fi'l-Hey'e", "Risâle fi'l-Hisâb", "Şerhu Zîc-i Uluğ Bey"],
    onemliOlaylar: ["Uluğ Bey rasathanesinde çalışma", "Semerkand'dan İstanbul'a yolculuk", "Fatih tarafından büyük ihsanla karşılandı", "Ayasofya Medresesi'nde hocalık"],
    katki: "Osmanlı astronomi ve matematik eğitimini Avrupa standartlarına taşıdı; trigonometri ve astronomiyi Osmanlı'ya aktardı",
    biliyorMuydun: "İstanbul'a varırken geçtiği her şehirde bir ilmi risâle yazdı ve hediye etti. Böylece 'yolda hediye getirmek' geleneğini bilimsel bir ritüele dönüştürdü."
  },
  {
    id: "ebussuud-efendi",
    sira: 19,
    ad: "Ebüssuûd Efendi — Muhammed b. Muhyiddin",
    lakap: "Şeyhu'l-İslâm — İslam Şeyhi",
    yasadi: "1490–1574",
    dogum: "İskilip (Çorum)",
    alan: "fikih",
    biyografi: "Osmanlı'nın en uzun süre görev yapan (28 yıl) ve en etkili Şeyhülislamı. Kanuni Sultan Süleyman döneminin yasal ve dini mimarı olan Ebüssuûd, örfî kanunları şer'î hukukla uzlaştıran fetvaları ve Kur'an tefsiriyle tarihe geçti.",
    eserler: ["İrşâdü'l-Akli's-Selîm — Tefsir (9 cilt)", "Dürerü'l-Hukkâm Şerhu Gureri'l-Ahkâm", "Ma'rûzât"],
    onemliOlaylar: ["28 yıl Şeyhülislamlık", "Kanunname'nin şer'i çerçevesini çizdi", "Tütün yasağı fetvası"],
    katki: "Osmanlı hukuk sistemini birleştirdi; kanun-şeriat dengesini kurdu; tefsir geleneğini zirveye taşıdı",
    biliyorMuydun: "Kanuni ile 50 yıllık arkadaşlıkları olduğu söylenir. Kanuni her sefer öncesinde ondan dua ve fetva alırdı. İkisi de aynı yıl (1566/1574) hayata gözlerini yumdu."
  },
  {
    id: "katip-celebi",
    sira: 20,
    ad: "Kâtip Çelebi — Mustafa b. Abdullah",
    lakap: "Hâcı Halîfe — Bilge Hacı",
    yasadi: "1609–1657",
    dogum: "İstanbul",
    alan: "tarih",
    biyografi: "Osmanlı'nın en büyük ansiklopedist ve bibliyografya âlimi. Askerî kâtiplik yaparak birçok sefere katıldı, bu süreçte kendi kendini yetiştirdi. Keşfü'z-Zünûn adlı eseri 14.500'den fazla kitabı kataloglayan dev bir bibliyografya ansiklopedisidir.",
    eserler: ["Keşfü'z-Zünûn (14.500 eser)", "Cihânnümâ — Coğrafya atlası", "Mîzânü'l-Hak", "Fezleke — Osmanlı tarihi"],
    onemliOlaylar: ["Koçi Bey ile tanışma", "Avrupa coğrafya kitaplarını Türkçeye çevirdi", "Ölümünde masasında yarım kalan eserleri bulundu"],
    katki: "Osmanlı'da bilimsel coğrafyanın kurucusu; en kapsamlı İslam bibliyografyasını oluşturdu",
    biliyorMuydun: "Kendi kendini yetiştirdi, hiçbir medresede düzenli eğitim almadı. 'Kitaplarımı miras olarak değil, yol azığı olarak biriktirdim' derdi."
  },
  {
    id: "bediuzzaman",
    sira: 21,
    ad: "Bediüzzaman Said Nursî",
    lakap: "Bediüzzaman — Zamanın Eşsizi",
    yasadi: "1878–1960",
    dogum: "Nurs köyü, Bitlis",
    alan: "kelam",
    biyografi: "Modern dönem İslam düşüncesinin en özgün seslerinden biri. Küçük yaşta olağanüstü bir zekâyla tüm medrese ilimlerini tamamladı. Risale-i Nur Külliyatı adıyla bilinen ve iman hakikatlerini aklî delillerle sunan dev eseriyle modern çağda İslam'ı yeniden yorumladı.",
    eserler: ["Risale-i Nur Külliyatı (130 risale)", "Sözler", "Mektubat", "Lemalar", "Şualar"],
    onemliOlaylar: ["I. Dünya Savaşı'nda esareti", "Tekke ve zaviyelerin kapatılması sürecinde sürgünler", "Defalarca mahkemeye verildi, beraat etti"],
    katki: "Modern pozitivizme karşı iman hakikatlerini akıl ve bilim diliyle savundu; Nur hareketi",
    biliyorMuydun: "Hayatı boyunca hiç evlenmedi, hiç köy dışına çıkmamışken 14 yaşına kadar bütün medrese ilimlerini bitirdi. 'Küçük Said' ve 'Büyük Said' olarak iki manevi dönemini kendisi tanımladı."
  },
  {
    id: "elmalili",
    sira: 22,
    ad: "Elmalılı Muhammed Hamdi Yazır",
    lakap: "Mufessir-i Kebîr — Büyük Müfessir",
    yasadi: "1878–1942",
    dogum: "Elmalı (Antalya)",
    alan: "tefsir",
    biyografi: "Türkçe Kur'an tefsirinin en büyük eseri olan Hak Dini Kur'an Dili'nin müellifi. İstanbul'da ileri düzey eğitim alarak medrese geleneğini en üst seviyede temsil etti. Diyanet İşleri Başkanlığı'nın talebiyle kaleme aldığı 9 ciltlik tefsiri bugün hâlâ temel başvuru kaynağıdır.",
    eserler: ["Hak Dini Kur'an Dili (9 cilt)", "İrşâdu'l-Ahlâf fî Ahkâmi'l-Evkaf", "Metalibü'l-Mütekaddimîn"],
    onemliOlaylar: ["Son Osmanlı Meclis-i Mebusanı üyesi", "Diyanet'in tefsir talebi ve 10 yıllık çalışma", "İşgal döneminde Anadolu'ya geçmedi, İstanbul'da kaldı"],
    katki: "Modern Türkçe'de Kur'an tefsirinin zirvesi; Osmanlı ilim geleneğini Cumhuriyet'e taşıdı",
    biliyorMuydun: "Tefsirini yazmak için 10 yıl dünyadan el etek çekti. Sabah namazından sonra başlayıp gece yarısına kadar çalışır, zaman zaman hasta yatağında bile yazmaya devam ederdi."
  }
];

// Quiz soruları
const QUIZ_SORULARI = [
  { soru: "el-Câmiu's-Sahîh adlı hadis kitabını kim derledi?", dogru: "imam-buhari", secenekler: ["imam-buhari", "imam-muslim", "imam-malik", "ahmed-ibn-hanbel"] },
  { soru: "İslam fıkhının dört mezhebinden birinin kurucusu olan ve 'İmâm-ı Âzam' lakabıyla tanınan alim kimdir?", dogru: "ebu-hanife", secenekler: ["ebu-hanife", "imam-safi", "imam-malik", "ahmed-ibn-hanbel"] },
  { soru: "el-Kânûn fi't-Tıb adlı eseriyle 600 yıl boyunca Avrupa üniversitelerinde ders kitabı okutulan alim kimdir?", dogru: "ibn-sina", secenekler: ["ibn-sina", "el-biruni", "ibn-rüsd", "imam-gazali"] },
  { soru: "'Hüccetu'l-İslâm' (İslam'ın Delili) lakabıyla anılan ve İhyâu Ulûmi'd-Dîn'in yazarı kimdir?", dogru: "imam-gazali", secenekler: ["imam-gazali", "ibn-teymiyye", "imam-safi", "ibn-arabi"] },
  { soru: "Sosyoloji ve tarih felsefesinin öncüsü sayılan ve Mukaddime'yi yazan alim kimdir?", dogru: "ibn-haldun", secenekler: ["ibn-haldun", "katip-celebi", "ibn-teymiyye", "el-biruni"] },
  { soru: "Mesnevi'nin yazarı ve Mevlevî tarikatının kurucusu kimdir?", dogru: "mevlana", secenekler: ["mevlana", "ibn-arabi", "haci-bayram-veli", "aksemsettin"] },
  { soru: "İstanbul'un manevi fatihi olarak anılan ve Fatih Sultan Mehmed'e hocalık yapan alim kimdir?", dogru: "aksemsettin", secenekler: ["aksemsettin", "haci-bayram-veli", "ali-kuscu", "ebussuud-efendi"] },
  { soru: "Keşfü'z-Zünûn adlı 14.500 kitaplık bibliyografyayı hazırlayan Osmanlı âlimi kimdir?", dogru: "katip-celebi", secenekler: ["katip-celebi", "ebussuud-efendi", "ibn-haldun", "elmalili"] },
  { soru: "Usûlü'l-fıkh ilminin kurucusu sayılan ve er-Risâle'yi yazan alim kimdir?", dogru: "imam-safi", secenekler: ["imam-safi", "ebu-hanife", "ahmed-ibn-hanbel", "imam-malik"] },
  { soru: "Vahdet-i Vücud nazariyesini sistematik biçimde geliştiren ve 'eş-Şeyhu'l-Ekber' lakabıyla anılan mutasavvıf kimdir?", dogru: "ibn-arabi", secenekler: ["ibn-arabi", "mevlana", "haci-bayram-veli", "imam-gazali"] },
  { soru: "Hak Dini Kur'an Dili adlı Türkçe tefsiri yazan alim kimdir?", dogru: "elmalili", secenekler: ["elmalili", "katip-celebi", "bediuzzaman", "ebussuud-efendi"] },
  { soru: "Amerika kıtasının varlığını hesap yoluyla öngören İslam bilim insanı kimdir?", dogru: "el-biruni", secenekler: ["el-biruni", "ibn-sina", "ali-kuscu", "katip-celebi"] },
  { soru: "Osmanlı'da 28 yıl Şeyhülislamlık yapan ve örfî-şer'î hukuku birleştiren alim kimdir?", dogru: "ebussuud-efendi", secenekler: ["ebussuud-efendi", "ali-kuscu", "katip-celebi", "elmalili"] },
  { soru: "Risale-i Nur Külliyatı'nın yazarı kimdir?", dogru: "bediuzzaman", secenekler: ["bediuzzaman", "elmalili", "katip-celebi", "ebussuud-efendi"] },
  { soru: "Mâddetü'l-Hayât adlı eserinde mikrop teorisini Pasteur'dan 400 yıl önce öngören alim kimdir?", dogru: "aksemsettin", secenekler: ["aksemsettin", "ibn-sina", "el-biruni", "ali-kuscu"] }
];
