// Silsile-i Aliyye — Nakşibendiyye Altın Zinciri
// 30 Halka: Hazret-i Muhammed Mustafâ (sallallahu aleyhi ve sellem)'dan
//           Hazret-i Mevlânâ Hâlid-i Bağdâdî (kuddise sirruh)'ya

const SILSILE = [
  {
    id: 1,
    ad: "Hazret-i Muhammed Mustafâ",
    tam_ad: "Hazret-i Muhammed Mustafâ (sallallahu aleyhi ve sellem)",
    lakap: "Habîbullâh, Hâtemü'l-Enbiyâ, Seyyidü'l-Mürselîn, Rahmeten li'l-Âlemîn",
    asir: "VII. Yüzyıl",
    dogum: "571", vefat: "632",
    sehir: "Medîne-i Münevvere", ulke: "Hicaz", bolge: "Hicaz",
    koordinat: [24.4672, 39.6119],
    biyografi: "Âlemlere rahmet olarak gönderilen Allahu Teâlâ'nın son peygamberi ve en sevgili kuludur. Her velînin velâyeti, her tarikatın silsilesi ve her mürşidin feyz ü nuru nihayetinde ona dayanır; o kapıya ulaşır. Nakşibendiyye'nin bu altın zinciri de onun mübarek kaynağından akar. Silsiledeki her isim, o nurü nesilden nesile taşıyan birer emânettir; her halka, onun sohbetinin ve nefesinin bir yansımasıdır. Mekke-i Mükerreme'de doğmuş, Medîne-i Münevvere'de Ravza-i Mutahhara'ya teşrif buyurmuştur. Ashâb-ı Kirâm'ın, Tâbiîn'in ve kıyamete dek gelecek bütün ümmetin kalpleri o kapıya bağlıdır.",
    portre: null
  },
  {
    id: 2,
    ad: "Hazret-i Ebû Bekir es-Sıddık",
    tam_ad: "Hazret-i Ebû Bekir es-Sıddık (radıyallahu anh)",
    lakap: "es-Sıddık, Halifetü Resulillah",
    asir: "VII. Yüzyıl",
    dogum: "573", vefat: "634",
    sehir: "Medîne-i Münevvere", ulke: "Hicaz", bolge: "Hicaz",
    koordinat: [24.4672, 39.6119],
    biyografi: "Hazret-i Muhammed Mustafâ (sallallahu aleyhi ve sellem)'ın en yakın dostu, ilk erkek mümini ve İslam'ın ilk halifesidir. Nakşibendiyye'de manevi terbiyenin hafi (gizli) yoluyla aktarımı ondan başlar. Medîne-i Münevvere'de Ravza-i Mutahhara'nın yanı başında medfundur.\n\nPeygamberlerden sonra, Eshâb-ı kiramın ve insanların en üstünü. Asıl adı Abdullah bin Ebû Kuhâfe bin Âmir bin Amr bin Ka’b bin Sa’d bin Teym bin Mürre’dir. Babasının adı Osman olup, Kuhâfe lakabıyla meşhûrdur. Annesinin adı ise Selmâ binti Sahr’dır. Ümmül -Hayr lakabıyla tanınmaktadır. Hazreti Ebû Bekir, Peygamber Efendimizden 2 yıl 3 ay küçüktür. Fil vak’asından sonra m. 573 yılında dünyâya gelmiştir. Müslüman olmadan önce adı, Abdüluzzâ veya Abdulkâ’be idi. Peygamberimize ( aleyhisselâm ) îmân ettikten son ra O’nun ismini “Abdullah” olarak değiştirdi. 38 yaşında müslüman olmakla şereflenen Hazreti Ebû Bekir; Peygamber efendimizin vefât ettiği gün halife seçildi. Hilâfeti 2 sene 3 ay 10 gün sürdü. 63 yaşında iken hicretin 13 (m. 634) yılında Cemaziyelâhir ayının yedisinde Pazartesi günü hastalandı. 15 gün hasta olarak yattıktan sonra vefât etti. Vasıyyeti üzerine, hanımı Esma yıkadı. Cenâze namazını Hazreti Ömer kıldırdı. Peygamber efendimizin kabrinin bulunduğu Hücre-i Se’âdete defn edildi. Ebû Bekir ( radıyallahü anh ) Aşere -i Mübeşşerenin yani Cennetle müjdelenen on sahabenin birincisidir. Peygamber efendimizin kayınpederi, Hazreti Âişe’nin babasıdır. Ebû Bekir ( radıyallahü anh )’ın Resûlullah efendimize fevkalâde sadâkat ve sevgisi vardı. Vefâtına, Peygamberimizden ( aleyhisselâm ) ayrıldığından duyduğu aşırı üzüntüsü, gammı ve hasreti sebep olmuştur. Çünkü O’na karşı olan, sevgisi ve bağlılığı kelimelerle tarif edilemiyecek kadar çoktur. Peygamber efendimiz de, Ebû Bekir’i ( radıyallahü anh ) çok severdi. O’nun için bizzat kendisine “Sen Allahü teâlânın Cehennemden atîki (yâni azâd ettiği kimse)sin” ve “Cehennemden atîk olan (âzâd edilmiş kimse) görüp sevinmek isteyen kimse, Ebû Bekir’e ba ksın” buyurması bunun bir alâmetidir.",
    portre: null
  },
  {
    id: 3,
    ad: "Hazret-i Selmân-ı Fârisî",
    tam_ad: "Hazret-i Selmân-ı Fârisî (radıyallahu anh)",
    lakap: "Ebu Abdillah, Selmânü'l-Hayr",
    asir: "VII. Yüzyıl",
    dogum: "~568", vefat: "~656",
    sehir: "Selmânpâk (Medâin yakını)", ulke: "Irak", bolge: "Mezopotamya",
    koordinat: [33.0956, 44.7642],
    biyografi: "İran'ın İsfahan yakınlarında doğmuş, uzun bir manevi arayışın ardından Hazret-i Muhammed Mustafâ (sallallahu aleyhi ve sellem)'e kavuşmuştur. Peygamber Efendimiz (sallallahu aleyhi ve sellem) onun hakkında 'Selmân bizdendir, Ehl-i Beyt'tendir' buyurmuştur. Silsilede Faris'ten gelen manevi akışın taşıyıcısıdır. Türbesi Bağdat yakınında Selmânpâk'tadır.\n\nEshâb-ı kiramın büyüklerinden ve meşhûrlarından. Silsilet -üz-Zeheb diye bilinen “Altın silsilenin” (Büyük veliler silsilesinin) ikinci halkası. Aslen İranlı olup, İsfehan yakınında bir köyde doğup, büyüdü. Gençliğinde mecûsî iken, hıristiyan rahibleriyle tanışı p, mecûsîliği terk etti. Kiliseye girip hıristiyan oldu. Çok ilim öğrenip âlim oldu. Sonra da uzun yıllar değişik yerlerde kaldı. Nihâyet Medine’ye gelip Peygamberimiz ( aleyhisselâm ) hicret edince maksadına kavuşup müslüman oldu ve Ehl -i beytten sayıldı. Müslüman olmadan önce, ismi Mabeh idi. Müslüman olunca, Peygamberimiz ( aleyhisselâm ), O’na Selmân ismini verdi. İranlı olduğu için de Fârisî denildiğinden ismi Selmân -ı Fârisî olarak meşhûr oldu. Nesebi ise; Mabeh bin Buzanşâh bin Mursilân bin Behbudah bin Firûz’dur. Lakabı Selmân-ül-Hayr, künyesi ise Ebû Abdullah’tır. Ebü’l-Ferec ( radıyallahü anh ) buyurdu ki: Abdullah İbn-i Abbâs’ın ( radıyallahü anh ) yanında idim. Bana Selmân-ı Fârisî’nin bir gün hayatını şöyle anlattı: Selmân dedi ki: “Ben Fâris (İran)’ın, İsfehan şehrinin Cey köyündenim. Babam köyün en zengini olup, arazîmiz ve malımız çoktu. Ben babamın tek çocuğu idim. Beni herkesten çok severdi. Bunun için beni kız gibi yetiştirdi. Evden çıkmama izin vermezdi. Babam mecûsî (ateşperest) olduğu için mecûsîliği de bana evde tam bir şekilde öğretti. Evde devamlı bir ateş yanar biz ona tapar secde ederdik. Babamın malı ve mülkü çok olduğu için beni bir ara dışarıya çıkardı ve dedi ki: “Yavrum ben öldüğüm zaman bu malların sahibi sen olacaksın, onun için git mallarını ve arazilerini tanı.” Ben de “peki” deyip bahçelerimizi dolaştım. Bir gün tarlalara bakmaya gittiğimde bir hıristiyan kilisesine rastladım. Onların seslerini işittim. Gidip baktım ki, içerde ibâdet ediyorlar.",
    portre: null
  },
  {
    id: 4,
    ad: "Hazret-i Kasım ibn Muhammed",
    tam_ad: "Hazret-i Kasım ibn Muhammed ibn Ebî Bekir (kuddise sirruh)",
    lakap: "Ebu Muhammed el-Medenî",
    asir: "VII–VIII. Yüzyıl",
    dogum: "~660", vefat: "~726",
    sehir: "Medîne-i Münevvere", ulke: "Hicaz", bolge: "Hicaz",
    koordinat: [24.4700, 39.6180],
    biyografi: "Hazret-i Ebû Bekir es-Sıddık (radıyallahu anh)'ın torunudur. Medîne-i Münevvere'nin ilim ve vera sahibi büyüklerindendi; fıkıh ve hadiste çağının imamı sayılmıştır. Manevi feyz Hazret-i Selmân-ı Fârisî (radıyallahu anh) vasıtasıyla ona ulaşmış, oradan Hazret-i Cafer-i Sâdık (kuddise sirruh)'a intikal etmiştir.\n\nTabiînin büyüklerinden, Medîne -i münevveredeki yedi büyük âlimden biri. İnsanları hakka da’vet eden onlara doğru yolu gösterip, hakiki se’âdete kavuşturan ve kendilerine “silsile -i âliyye” denilen büyük âlim ve velîlerin üçüncüsüdür. Adı, Kâsım bin Muhammed bin Ebû Bekr- i Sıddîk et -Teymî’dir. Babası Muhammed, Hazreti Ebû Bekir’in oğludur. Annesi Sevde, Yezdücerd’in kızı olduğundan, İmâm -ı Zeynel-âbidin ile teyze çocuklarıdır. Babası Mısır’da şehîd edilip küçük yaşta yetim kalınca, halası ve Peygamberimizin mübârek hanımı Hazreti Âişe’nin, yanında büyüdü. Tabiîn devrinde ve Hazreti Osman’ın hilâfeti zamanında 31 (m. 653) yılında doğdu ve 101 (m. 721) veya 106 (m. 725) yılında Mekke ile Medîne arasında Kudeyd denilen yerde hacca veya umreye giderken vefât etti. Kâsım bin Muhammed, Hazreti Ebû Bekr -i Sıddîk’ın torunudur. Eshâb -ı kiramdan birçoğuna yetişmiş ve onlardan birçok ilim öğrenip başta halası Hazreti Âişe, Ebû Hüreyre, Abdullah İbni Abbâs ve Abdullah İbni Ömer, Hazreti Muâviye gibi meşhûr sahâbîlerden hadî s-i şerîf rivâyetinde bulunmuştur. Kendisinden de, Tabiînin büyüklerinden oğlu Abdurrahmân, Sâlim bin Abdullah, İmâm-ı Şa’bî, akranlarından İbn-i Amr, Yahyâ bin Saîd ve Sa’d bin Saîd el -Ensârî, Abdullah bin Ömer, Sa’d bin İbrâhîm, Abdullah bin Avn ve daha birçoğu hadîs-i şerîf rivâyet etmişlerdir. Tasavvuf ilminde mütehassıs idi. Vera’ ve takvâda (Allahü teâlânın haram ettiklerinden sakınıp kaçınmada) eşi yoktu. Dedesi Ebû Bekr-i Sıddîk ( radıyallahü anh ) Peygamber efendimizden ve Peygamberlerden sonra insanların en üstünü oldu. Resûlullahdaki bütün üstünlükler, ilimler ve feyizler onda toplanmış ve her bakımdan üstün olmuştur. Kalbe, rûha âit ilimlerin kaynağı i di.",
    portre: null
  },
  {
    id: 5,
    ad: "Hazret-i Cafer-i Sâdık",
    tam_ad: "Hazret-i Cafer-i Sâdık (kuddise sirruh)",
    lakap: "es-Sâdık, İmâmü's-Sâdıkın",
    asir: "VIII. Yüzyıl",
    dogum: "702", vefat: "765",
    sehir: "Medîne-i Münevvere", ulke: "Hicaz", bolge: "Hicaz",
    koordinat: [24.4660, 39.6100],
    biyografi: "Hazret-i Ali (radıyallahu anh)'nin mübarek neslinden, Ehl-i Beyt'in büyük imamıdır. Hem zâhir hem bâtın ilimlerinde çağının pınarı idi; pek çok büyük alim ondan istifade etmiştir. Medîne-i Münevvere'de Bakî kabristanında medfundur.\n\nİslâm âlimlerinin gözbebeklerinden olup, seyyid ve oniki imâmın altıncısı. Hazret -i Ali’nin torununun torunu olup, Eshâb-ı kiramı görmekle şereflenen Tabiîn devrinin yükseklerinden ve evliyânın büyüklerinden olup, silsile -i âliyyenin dördüncüsüdür. Künyesi , “Ebû Abdullah”dır. Tâhir, Fadıl gibi birçok lakabı vardır. En meşhûru “Sâdık”tır. Babası Muhammed Bâkır, onun babası İmâm-ı Zeynel’âbidîn, onun babası Hazreti Hüseyin ve onun babası da Hazreti Ali’dir. Annesi Ümmü Ferve’dir. Annesinin babası Kâsım, onun babası Muhammed ve onun babası da Hazreti Ebû Bekr-i Sıddîk’tır. Annesinin annesi, Abdurrahmân bin Ebû Bekr’in kızı Esmâ’dır. 83 (19 Nisan Çarşamba m. 702) senesinin Rebîul -evvel ayının onyedisinde Pazartesi günü Medîne-i münevverede doğdu. Altmışbeş senelik ömrünün otuzdört senesinde imamlık yaptı. 148 (6 Eylül Cuma m. 765) senesinin Recep ayının onbeşinde Pazartesi günü Mekke’de vefât etti. Kabri, Cennet-ül-Bâki’de olup, babası ve dedesi yanındadır. Ca’fer-i Sâdık hazretleri, temiz ve yüksek bir nesebe (soya) sahip olduğu gibi, güzel yüzlü ve tatlı dilliydi. Bedeni sanki nûr saçıyordu. Yüzünün renginde beyaz ve kırmızı karışmış olup, tatlı bir çehresi vardı. Kuvvetli ve orta boylu idi. Kısa ve şişman değildi. Saçı kumrala yakındı. Hazreti Ali’ye çok benzerdi. On evlâdı olup, yedisi erkek, üçü kız idi. Oğulları: Mûsâ Kâzım, İshâk, Muhammed, İsmail, Abdullah, Abbâs ve Ali’dir. Evlâdlarının hepsi zamanının süsü, âlimi ve üstünlerinden olup, evliyânın rehberiydiler. Mûsâ Kâzım, oniki imâmın yedincisidir. İmâm-ı Ca’fer ilmi, oniki imâmdan beşincisi olan babası Muhammed Bâkır’dan öğrendi. İlim ve fazîlette zamanının bir tanesi oldu. Bütün din bilgilerinde olduğu gibi, zamanının bütün fen ilimlerinde de söz sahibiydi.",
    portre: null
  },
  {
    id: 6,
    ad: "Hazret-i Bâyezîd-i Bistâmî",
    tam_ad: "Hazret-i Bâyezîd-i Bistâmî (kuddise sirruh)",
    lakap: "Sultânü'l-Ârifîn",
    asir: "IX. Yüzyıl",
    dogum: "~804", vefat: "~874",
    sehir: "Bistam", ulke: "İran", bolge: "Horasan",
    koordinat: [36.4174, 54.2850],
    biyografi: "İran'ın Bistam şehrinde doğup vefat etmiştir. 'Sultânü'l-Ârifîn' lakabıyla anılan büyük velîdir. İslam tasavvuf tarihinde fenâ fillah ve sekr makamını ilk sistematik biçimde dile getirenlerdendir. Türbesi Bistam'da hâlâ ziyaret edilmektedir.\n\nEvliyânın büyüklerinden. İnsanları Hakka da’vet eden, onlara doğru yolu gösterip, hakîkî se’âdete kavuşturan ve kendilerine “Silsile-i aliyye” denilen büyük âlim ve velîlerin beşincisidir. “Sultân-ül-ârifîn” lakabıyla meşhûrdur . Künyesi, Ebû Yezîd’dir. İsmi Tayfur, babasının adı Îsâ’dır. 160 veya 188 (m. 803)’de İran’da Hazar Denizi kenarında Bistâm’da doğdu. 231 veya 261 (m. 874) senesinde Şabân -ı şerîfin onbeşinci günü Bistâm’da vefât etti. Hanefî mezhebinde idi. Annesi diyor ki, “Kendisine hâmile iken şüpheli bir şeyi ağzıma alacak olsam, onu geri atıncaya kadar karnıma vururdu.” Üveysî olup, İmâm -ı Ca’fer -i Sâdık’ın vefâtından kırk yıl sonra doğdu. İmâm -ı Ali Rızâ’nın sohbetinden ve bunun bereketiyle İmâm -ı Ca’fer -i Sâdık’ın rûhâniyetinden istifâde etmiştir. Hazreti Bâyezîd, İmâm-ı Ca’fer-i Sâdık’ın rûhâniyetinden feyz almakla meşhûr olmuştur. Otuz sene Şam civarında bulunup, yüzonüç âlimden ilim öğrenmiştir. Aşk -ı ilâhîde o kadar ileri ve ibâdette o derece yüksekte idi ki, namaz kılarken Allah korkusundan ve İslâmiyete saygısından göğüs kemikleri gıcırdar, yanında bulunanlar bunu işitirlerdi. Son derece âlim, fadıl ve edîb idi. Şiirleri meşhûrdur. Hazreti Bâyezîd, ilim tahsil ettiği üstâdlarından birine olan hürmet ve muhabbetinden dolayı, onun kabrinin yanına defn edilmeyi ve kabrinin, hocasının kabrinden, daha derin yapılmasını, kendi vücûdunun, hocasının vücûdundan aşağıda olmasını vasıyyet etti. Hocalarının en büyüğü, Allahü teâlâya kavuşmak yolunda çok yüksek derecelere kavuşmasına vesîle olan, İmâm-ı Ca’fer -i Sâdık hazretleridir.",
    portre: null
  },
  {
    id: 7,
    ad: "Hazret-i Ebü'l-Hasan Harakânî",
    tam_ad: "Hazret-i Ebü'l-Hasan Harakânî (kuddise sirruh)",
    lakap: "Şeyhü'l-İslâm",
    asir: "X–XI. Yüzyıl",
    dogum: "~963", vefat: "1033",
    sehir: "Hârakân", ulke: "İran", bolge: "Horasan",
    koordinat: [36.4500, 49.5000],
    biyografi: "Kazvin yakınlarındaki Hârakân köyünden yetişmiş büyük velîdir. Üveysî yolla Hazret-i Bâyezîd-i Bistâmî (kuddise sirruh)'den feyz almış; Muhyiddin İbnü'l-Arabî ve Ferîdüddin Attâr onu büyük övgüyle anmıştır. Türbesi hâlâ Hârakân'dadır.\n\nAllahü teâlâya ve âhırete âit ilimler ya’nî ma’rifetler sahibi büyük bir âlim. Künyesi Ebü’l-Hasen olup ismi Ali bin Ca’fer’dir. Bistâm’ın bir kasabası olan Harkân’da dünyâya geldi. Ebü’l-Hasen- i Harkânî, uzun boylu, güzel yüzlü, geniş alınlı, iri gözlü ve kumral idi. Hazreti Ömer’e benzerdi, insanları hakka da’vet eden, onlara doğru yolu gösterip, hakiki saadete kavuşturan ve kendilerine silsile-i âliyye denilen büyük âlim ve velilerin altıncısıdır. Büyük İslâm âlimi Bâyezîd- i Bistâmî’nin rûhâniyetinden istifâde ederek kemâle gelmiş, yükselmişti. Zamanının kutbu idi. 425 (m. 1034) senesinde Harkân’da vefât etti. Ebü’l-Hasen-i Harkânî hazretleri, oniki sene Harkân’dan Bistâm’a, hocasının kabrini ziyâret için gitti. Bu ziyârete giderken, yolda Kurân -ı kerîmi hatim ederdi. Her gittiğinde ziyâret ile ilgili vazîfelerini yaptıktan sonra, “Yâ Rabbî! Bâyezîd’e ihsân etti ğin sana âit ilimlerden, büyüklüğünün hakkı için, Ebü’l -Hasen kuluna da ihsân eyle” diye yalvarırdı. Gerî dönerken, hiçbir zaman Bâyezîd’in türbesine arkasını dönmezdi. Yatsı ve sabah namazlarını türbede kılardı. Oniki sene sonra, Allahü teâlânın lütfu ile Bâyezîd’in rûhaniyetinden istifâde edip olgunlaştı. Allahü teâlâyı tanıtan kalb ilimlerinde ve diğer ilimlerde talebe yetiştirmeye başladı. Pekçok talebesi vardı. Kerâmetleri, menkıbeleri ve veciz sözleri çoktur. Çok anlatılan kerâmetlerinden biri de şudur: Bir kâfilede bulunan insanlar, üstadın huzûruna gelip “Yollar korkuludur. Bize bir duâ öğretiniz” diye istirhâm edince; buyurdu ki: “O zaman, Ebü’l -Hasen’i hatırınıza getiriniz!” Bu söz, gelenlerin hoşlarına gitmedi. Yolda eşkiya, önlerine çıktı. Hepsinin mal ve meta’larını aldı. Yalnız, Ebü’l-Hasen-i Harkânî hazretlerini hatırlayan bir kimsenin malına zarar gelmedi.",
    portre: null
  },
  {
    id: 8,
    ad: "Hazret-i Ebû Alî Fârmedî",
    tam_ad: "Hazret-i Ebû Alî Fârmedî (kuddise sirruh)",
    lakap: "Kutbü'l-Aktâb",
    asir: "XI. Yüzyıl",
    dogum: "~1042", vefat: "1084",
    sehir: "Tûs (Nîşâbur yakını)", ulke: "İran", bolge: "Horasan",
    koordinat: [36.2719, 59.6134],
    biyografi: "İmam Gazzâlî'nin irşat yolculuğundaki mürşididir. Nişabur ve Tus'ta pek çok talebe yetiştirmiştir. Hem Nakşibendiyye hem de Kâdiriyye silsilelerinin önemli bir halkasıdır. Feyzini Hazret-i Ebü'l-Hasan Harakânî (kuddise sirruh)'den almıştır.\n\nHorasan’da yetişen evliyânın büyüklerinden. İsmi, Fadl bin Muhammed’dir. 433 (m. 1042) senesinde doğdu. Yaşadığı devrin âlimleri arasında bir tane idi. Zâhirî din ilimlerini, Ebü’l - Kâsım Kuşeyrî hazretlerinden öğrendi. Ayrıca Ebû Abdullah Muhammed bin Muha mmed Şirâzî, Ebû Mensûr Temimî, Ebû Abdurrahmân Neylî, Ebû Osman Sabûnî ve daha başka âlimlerden de ilim tahsil etti. Sözü, nasihatları pek te’sîrli idi. Selçuklu devletinin meşhûr veziri Nizâm-ül-mülk ve zamanının devlet erkânı, ona çok hürmet ederdi. 478 (m. 1085) senesinde vefât etti. Kabri Tûs ya’nî Meşhed şehrindedir. Tasavvuf ilminde yüksek derecelere kavuşması iki vasıta ile olmuştur. Birisi Ebü’l -Kâsım Gürgânî-i Tûsî diğeri de Ebü’l -Hasen-i Harkânî’dir. Ebû Ali Fârmedî, insanların i’tikâd, amel, ibâdet ve ahlâk husûsunda doğruyu öğrenmeleri ve yapmaları, böylece Allahü teâlânın rızâsına kavuşmaları için onlara rehberlik edip, buna kavuşturan ve kendilerine silsile -i aliyye denilen meşhûr velilerden olup, bu âlimlerin yedincisidir. Rûh ilimlerinin mütehassısı idi. Ebû Saîd-i Ebülhayr’dan da istifâde ederek feyz aldı. Hocası Ebu’l-Kâsım-ı Gürgânî, Ebû Osman-ı Magribî’nin, bu da Cüneyd-i Bağdadî hazretlerinin talebesi olup, herbirisi, insanlara doğru yolu göstermek için yetişmiş yetkili kimselerdir. Ebû Ali Fârmedî hazretleri, hem İmâm-ı Gazâlî, hem de Yûsuf-i Hemedânî hazretlerinin hocası idi. Her ikisi de ondan istifâde ederek kemale gelmiş, yüksek derecelere kavuşmuştur. Tasavvuf yoluna girişini, bizzat kendisi şöyle anlatır: “Gençliğimin başlangıcında, Nişâbûr’da ilim öğrenmekle meşgûl idim. Ebû Sa’îd -i Ebülhayr hazretleri ilim meclisimize teşrîf ettiler. Hemen huzûrlarına gelip hizmete başladım. Hallerindeki ve yüzündeki güzelliğe âşık olmuştum.",
    portre: null
  },
  {
    id: 9,
    ad: "Hazret-i Yûsuf-ı Hemedânî",
    tam_ad: "Hazret-i Yûsuf-ı Hemedânî (kuddise sirruh)",
    lakap: "Kutbü'l-Meşâyih",
    asir: "XI–XII. Yüzyıl",
    dogum: "1049", vefat: "1140",
    sehir: "Merv", ulke: "Türkmenistan", bolge: "Mâverâünnehr",
    koordinat: [37.6394, 62.1873],
    biyografi: "Hemedan doğumlu olup Merv'e yerleşmiştir. Hacegân silsilesinin Orta Asya'ya taşınmasındaki en büyük köprü mesabesindedir. Yetiştirdiği halifeler arasında Hazret-i Ahmed Yesevî (kuddise sirruh) ve Hazret-i Abdülhâlik Gücdevânî (kuddise sirruh) bulunmakta olup bu iki isim Türk-İslam tasavvufunun iki büyük kanalını oluşturmuştur.\n\nEvliyânın büyüklerinden. İsmi, Yûsuf bin Ya’kûb Hemedânî olup, Künyesi Ebû Ya’kûb’dur. İnsanları hakka da’vet eden, onlara doğru yolu gösterip, hakîkî saadete kavuşturan ve kendilerine “Silsile -i âliyye” denilen büyük âlim ve velîlerin sekizincisidir. 440 (m. 1048) senesinde Hemedan’da doğdu. 535 (m. 1140)’de Herat’tan Merve giderken yolda vefât etti. Onsekiz yaşında iken Bağdad’a gelip, fıkıh ilmini Ebû İshâk -i Şîrâzî’den öğrendi. Yaşı küçük olmasına rağmen, Ebû İshâk ( radıyallahü anh ) kendisine husûsî ihtimâm gösterirdi. Bunun ve diğer fıkıh âlimlerinin derslerine devâm etmekle, Hanefî mezhebinde fı kıh ve münâzara âlimi oldu. İsfehan ve Semerkand’da, zamanın meşhûr hadîs âlimlerinden hadîs ilmini öğrendi. Tasavvufu Ebû Ali Fârmedî hazretlerinden öğrenip, onun sohbetinde yetişerek kemâle ulaştı. Abdullah-ı Cüveynî, Hasen Simnânî ve birçok büyük zâtlar ile görüşüp, sohbet etti. Kendilerinden ilim öğrendi. Altmış yıldan fazla, insanlara doğru yolu göstermekle meşgûl oldu. Yüzlerce talebe ondan ders aldı. Abdullah-i Berkî, Hasen-i Endâkî, Ahmed Yesevî ve Abdülhâlık-ı Goncdüvânî gibi büyük velîler yetiştirdi. Bunlardan Ahmed Yesevî, Türkistan tarafına göç edip, insanları irşâd ederek büyük hizmetler yaptı. Yûsuf -i Hemedânî, bütün dostlarına, talebesi Abdülhâlık -ı Goncdüvânî’ye tâbi olmalarını söyledi. Kendisinden sonra, bu talebesi insanlara doğru yolu gösterdi. Yûsuf-i Hemedânî ( radıyallahü anh ), önce Merv şehrinde bir müdâet kalıp Hirat’a gitti. Hirat’ta uzun zaman kaldıktan sonra, tekrar Merv’e gelip bir müddet daha orada kaldı ve Hirat’a döndü. Hirat’tan Merv’e yolculuğu sırasında vefât etti. Kabri Merv şehrinde olup, ziyâret edilmektedir. Yûsuf-i Hemedânî, İmâm-ı a’zama pekçok bağlı idi.",
    portre: null
  },
  {
    id: 10,
    ad: "Hazret-i Abdülhâlik Gücdevânî",
    tam_ad: "Hazret-i Abdülhâlik Gücdevânî (kuddise sirruh)",
    lakap: "Hazret-i Hvâce",
    asir: "XII. Yüzyıl",
    dogum: "~1103", vefat: "1179",
    sehir: "Gücdevân (Buhara yakını)", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [40.1047, 64.6801],
    biyografi: "Nakşibendiyye'nin temel prensiplerini (kelimât-ı kudsiyye) ilk defa bir bütün hâlinde ortaya koyan büyük mürşiddir. Gizli zikrin (zikr-i hafî) sistemini kurmuş; 'Dilde Hak, elde halk' düsturunu yaşamıştır. Buhara yakınlarındaki Gücdevân'da medfundur.\n\nEvliyânın önderlerinden, İslâm âlimlerinin büyüklerindendir. Babası Abdülcemîl, âlim ve ârif bir kimse olup, Malatyalı idi. İmâm -ı Mâlik hazretlerinin soyundandır. Zâhirî ve bâtınî ilimlerde üstün olup, müşkülü olanlar ona başvururdu. Hızır aleyhisselâm ile görüşür, sohbet ederlerdi. Birgün Hızır (aleyhisselâm) kendisine: “Senin sâlih bir erkek evlâdın olacak, ismini Abdülhâlık koyarsın!” buyurdular. Çocuk doğmadan Abdülcemîl ( radıyallahü anh ) Buhârâ’ya göç etti. Goncdüvân kasabasına yerleşti. Abdülhâlık Goncdüvânî orada doğdu. Çocukluğunu burada geçirdi. Yine burada 575 (m. 1179) târihinde vefât etti. Abdülhâlık Goncdüvânî hazretleri, ilim öğrenmek için, beş yaşında iken Buhârâ’ya gönderildi. Buhârâ’nın büyük âlimlerinden Hâce Sadreddîn’den ( radıyallahü anh ) Kur’ân -ı kerîm ve tefsîrini öğrenmeye başladı. Okuma esnasında “Rabbinize tezarrû’ ederek ve g izli duâ ediniz” (A’râf-55) meâlindeki âyet-i kerîmeye gelince hocasına; “Efendim! Bu “gizli”den murâd edilen nedir? Kalb ile yapılan zikrin aslı nedir? Eğer zikir ve duâ, aşikâr (açıktan, sesli olarak), dil ile olursa riyadan korkulur. Araya riya girerse, hakkı ile (lâyık olduğu şekilde) zikir edilmemiş olur. Şayet kalb ile zikretsem, “Şeytan insanın damarlarında kan gibi dolaşır” hadîs-i şerîfi gereğince, şeytan bu zikri duyar. Ne yapacağımı bilemiyorum, bu müşkülümü halletmenizi istirhâm ederim, efendim!” diye arz etti. Hocası, büyük âlim Sadreddîn hazretleri, bu yaştaki bir çocuğun kendisinin bile anlıyamadığı böyle bir suâl sorabilmesine hayret etti, hayran kaldı. Cevâb olarak, “Evlâdım! Bu mes’ele, kalb ilimlerinin bir konusudur. Allahü teâlâ nasîb ederse, sana bu ilimleri öğretebilecek bir üstada kavuşturur. Kalb ile zikri ondan öğrenirsin, böylece bu müşkülün halledilmiş olur” buyurdu.",
    portre: null
  },
  {
    id: 11,
    ad: "Hazret-i Ârif-i Rîvegerî",
    tam_ad: "Hazret-i Ârif-i Rîvegerî (kuddise sirruh)",
    lakap: "Hvâce Ârif",
    asir: "XII–XIII. Yüzyıl",
    dogum: "?", vefat: "~1239",
    sehir: "Rîveger (Buhara yakını)", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [39.8000, 64.4500],
    biyografi: "Hazret-i Abdülhâlik Gücdevânî (kuddise sirruh)'nin en has ve yüksek halifesidir. Buhara civarındaki Rîveger köyünde yaşamış ve orada defnedilmiştir. Silsilede derin sükûnet ve hakikat anlayışıyla temayüz etmiş büyük bir velîdir.\n\nPeygamberimizin ( aleyhisselâm ) ve Eshâbının yolunu insanlara öğreten büyük âlim ve velî. Aslen Buhârâlıdır. Buhârâ’ya 30 km. uzaklıkta bulunan Rîvgir kasabasında doğmuştur. Doğum târihi kat’î olarak bilinmemektedir. Peygamber efendimizden sonra insanlara doğru yolu gösteren âlimler silsilesinin onuncusudur. Medrese tahsili görüp, zâhirî ilimlerde büyük gayret ve çalışma gösterirdi. Hocası kendisini çok sever ve takdîr ederdi. Bu tahsil sırasında Ârif-i Rîvegerî, birgün çarşıda büyük âlim Abdülhâlık- ı Goncdüvânî’ye rastladı. Baktı ki, şeyh yüklenmiş evine erza k götürüyor. Edeple yaklaşarak eşyaları taşımak için izin istedi. Şeyh yükünü Ârife verdi ve beraberce eve gittiler. Eşyaları bıraktıktan sonra, “Bir saat sonra gel, yemeği beraber yiyelim” da’vetini aldı. Rîvegerî evden ayrıldıktan sonra, kendisinde bir b oşluk hissetti. Kalbindeki bu boşlukta, sâdece Abdülhâlık -ı Goncdüvânî’ye karşı hizmet aşkı vardı. Bir saat sonra eve gitti, iltifâtlar görüp, evlâtlığa kabûl edildi. Hocası tarafından ma’nevî ilimler ve evliyâlık yolunun esasları öğretilmeye başlandı. Ârif-i Rîvegerî, hep bunlarla meşgûl olup medreseye ve eski hocasına dönmedi. Ârif-i Rîvegerî’yi her gördükte eski hocası azarlıyor, hakaret ediyor, medreseye dönmesi için baskı yapıyordu. O, her seferinde mukâbele etmiyor, hiç sesini çıkarmıyordu. Bir gece eski hocası, kendisine ve bir müslümana yakışmayacak bir günah işledi. Ertes i gün o Ârifi gördüğünde, yine hakarete başlayınca, Ârif -i Rîvegerî ona şunları söyledi: “Hocam, niye hep benim gibi bir gariple uğraşırsın? Sen, dün gece büyük bir günah işledin; kendi hatânız yetmiyormuş gibi, beni de doğru yoldan ayırmak istiyorsun.” Bu nu duyan eski hocası çok utandı. Eski talebesinin durumunu anladı, tövbe etti. Abdülhâlık -ı Goncdüvânî’ye gidip talebe oldu.",
    portre: null
  },
  {
    id: 12,
    ad: "Hazret-i Mahmûd-ı İncirfağnevî",
    tam_ad: "Hazret-i Mahmûd-ı İncirfağnevî (kuddise sirruh)",
    lakap: "Hvâce Mahmûd",
    asir: "XIII. Yüzyıl",
    dogum: "?", vefat: "~1272",
    sehir: "İncirfağne (Buhara yakını)", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [39.8500, 64.3000],
    biyografi: "Buhara'nın İncirfağne köyünden yetişmiş büyük velîdir. Moğol istilasının en şiddetli döneminde Mâverâünnehr'de tasavvuf ateşini canlı tutmuştur. Silsilenin bu karanlık dönemde kesintisiz devam etmesini sağlamıştır.\n\nİslâm âlimlerinin büyüklerinden. İnsanları Hakka da’vet eden, onlara doğru yolu gösterip, hakiki saadete kavuşturan ve kendilerine “Silsile-i âliyye” denilen büyük âlim ve velilerin onbirincisidir. Mâverâünnehr ilinin (bölgesinin) Tûr-i Sina gibi mukaddes bir yer olmasına vesile olan, orayı nûrlandıran büyük âlim ve velîlerden olan Mahmûd -i İncirfagnevî ( radıyallahü anh ), Buhârâ’nın Fagne köyünde doğdu ve Akbenî nahiyesinde yerleşti. Doğum târihi tesbit edilememiştir. 715 (m. 1315) senesinde Vefât etti. Mi’mârlık ile geçinirdi. Hâce Ârif-i Rîvegerî hazretlerinin derslerinde ve sohbetlerinde yetişip, kemâle geldi. Maddî ve ma’nevî ilimlerde zamanının en büyük âlimlerinden oldu. İnsanları irşâd etmek (onlara saadet yolunu göstermek) için hocasından icâzet aldı. Birçok âlim yetiştir di. Binlerce kimsenin, dalâletten hidâyete (doğru yola, saadete) kavuşmasına vesile oldu. Yetiştirdiği âlimlerin en büyüğü ve kendisinden sonra halîfesi Hâce Ali Râmîtenî hazretleridir. Hocası Ârif-i Rîvegerî’den icâzet alıp, insanları doğru yola irşâd ile vazîfelendirilince, vaktin gereği olarak sesli zikre başladı. Sesli zikre ilk başlaması, hocası Hâce Ârif-i Rîvegerî’nin vefât hastalığı sırasında, Rîveger tepesi üzerinde olmuştu. Hâce Ârif bu zaman; “Şimdi vaktidir” buyurdu. Bu sözünü, kabûlüne işâret tutmuşlardır. Hâce Ârif Rîvegerî’nin vefâtından sonra, Kale Kapısı önündeki mescidde sesli zikre devam eyledi. Vaktinin büyük âlimlerinden olan Hâce Muhammed Pârisâ’nın dedelerinden Mevlânâ Hâfızuddîn, âlimlerin üstadı Şemsüleimme Hulvânî’nin işâreti ile, Buhârâ’da, o zamanın en büyük İmâm ve âlimlerinin huzûrunda, Hâce Mahmûd’a; “Siz hangi niyetle cehri (sesli) zikr ile meşgûl oluyorsunuz?” diye sordu.",
    portre: null
  },
  {
    id: 13,
    ad: "Hazret-i Alî Râmitenî",
    tam_ad: "Hazret-i Alî Râmitenî (kuddise sirruh)",
    lakap: "Hvâce Azîzân",
    asir: "XIII–XIV. Yüzyıl",
    dogum: "~1195", vefat: "~1306",
    sehir: "Râmiten (Buhara yakını)", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [40.0500, 64.3500],
    biyografi: "'Hvâce Azîzân' (Azizler Efendisi) lakabıyla tanınmıştır. Buhara yakınlarındaki Râmiten'de uzun yıllar mürid yetiştirmiştir. İlim, ahlak ve maneviyat bakımından döneminin başvuru kaynağı olan bu büyük velî yüz yaşını aşkın bir ömür sürmüştür.\n\nİslâm âlimlerinin büyüklerinden. “Hâce Azîzân” ve “Pîr -i Nessâc” isimleri ile meşhûrdur. Mahmûd-i İncirfagnevî’nin talebesidir. Buhârâ’ya onbeş kilometre olan Râmiten köyünde doğdu. Râmiten’de ilim tahsiline başladı. Çok kısa zamanda ilim yolunda mertebeler katetti. O devrin en büyük âlimi olan Hâce Mahmûd -i İncirfagnevî’nin derslerine büyük bir aşkla devam etti. Hocasının iltifâtlarına kavuştu. Ma’nevî ve maddî ilimlerde kemâle erdi. Böylece zamanın en büyük âlimlerinden, yol göstericilerinden oldu. Öyle ki, şaşırmışların sığınağı, doğru yoldan ayrılanların rehberi, hakka da’vet edenlerin büyüklerinden oldu. Ali Râmîtenî ( radıyallahü anh ), silsile -i âliyye denilen büyüklerin teşkil ettiği altın halkalar diye isimlendirilen Hak yolu zincirinin onikinci hal kası olma şerefine kavuştu. Helâl lokma kazanmak için dokumacılık yapardı. Yüksek makamlar, şaşılacak kerâmetler sahibi idi. 721 veya 728 (m. 1328)’de yüzotuz yaşında Hârezm şehrinde vefât etti. İhtiyâç sahipleri kabrini ziyâret ederek, mübârek rûhâniyetinden istifâde etmektedir. Ali Râmîtenî hazretlerine, “Azîzân” denmesinin sebebi şöyle anlatılır: Bir zaman Ali Râmîtenî’nin evinde iki -üç gün yiyecek birşey bulunmadı. Evdekiler açlık sebebiyle çok üzülüyorlardı. Gelen misâfire de evde ikram edecek birşey yoktu. O sırada Ali Râmîte nî hazretlerinin talebelerinden yiyecek satan bir genç, pirinç doldurulmuş bir horoz hediye getirdi. “Bu yemeği, sizin ve yakınlarınız için hazırladım. Eğer hediyemizi kabûl buyurursanız, bizi memnun edersiniz” diyerek yalvardı. Bu nâzik anda gelen yemekten son derece hoşnut olup, o talebesine iltifâtlarda bulundu. Bu yemeği, misâfirine ikram ederek ağırladı. Misâfir gittikten sonra o talebesini çağırtarak; “Getirdiğin bu yemek, sıkıntılı bir ânımızda imdâda yetişti.",
    portre: null
  },
  {
    id: 14,
    ad: "Hazret-i Muhammed Bâbâ Semmâsî",
    tam_ad: "Hazret-i Muhammed Bâbâ Semmâsî (kuddise sirruh)",
    lakap: "Hvâce Bâbâ",
    asir: "XIV. Yüzyıl",
    dogum: "?", vefat: "1354",
    sehir: "Semmâs (Buhara yakını)", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [39.8000, 64.6000],
    biyografi: "Hazret-i Muhammed Bahâeddin Şâh Nakşibend'in (kuddise sirruh) mürşidinin mürşididir. Buhara civarındaki Semmâs köyündendir. Manevi terbiyedeki hassasiyeti ve derin hikmeti ile tanınmıştır. Halifesi Hazret-i Seyyid Emîr Külâl (kuddise sirruh) aracılığıyla bu nurlu emaneti devam ettirmiştir.\n\nHâce Ali Râmîtenî hazretlerinin yetiştirdiği evliyânın büyüklerinden. Kendilerine Silsile-i âliyye denilen büyük İslâm âlimlerinin onüçüncüsüdür. Râmîten ile Buhârâ arasında bulunan ve Râmîten’e iki kilometre, Buhârâ’ya ise altı kilometre uzaklıkta bulunan Semmâs köyünde doğdu. 755 (m. 1354)’de orada vefât etti. Tasavvuf ilmini büyük âlim Ali Râmîtenî’den öğrendi. Onun derslerinde ve sohbetlerinde yetişip, tasavvufda yüksek dereceye ulaştı. Hocası, kendisinden sonra irşâd makamına Muhammed Bâbâ Semmâsî’yi v ekîl bıraktı. Diğer talebelerine de, ona tâbi olmalarını vasıyyet etti. Hocasının vefâtından sonra irşâd makamına geçen Muhammed Bâbâ Semmâsî, çok talebe yetiştirdi ve içlerinden bir kısmını tasavvufda yüksek makamlara kavuşturdu. Bu talebelerinin başında, kendisinden sonra yerine geçen ve ilim deryasında sadef misâli olan Sey yid Emîr Külâl hazretleri gelmektedir. Bir talebesi de, Şâh-ı Nakşibend Behâüddîn-i Buhârî hazretleridir. Behâüddîn Nakşibend hazretleri, Kasr-ı Hindüvân’da doğdu. Henüz o doğmadan evvel, hocası Muhammed Bâbâ Semmâsî onun doğduğu yerden geçerken; “Bu yerde n büyük bir zâtın kokusu geliyor. Pek yakında Kasr-ı Hindüvân, Kasr-ı ârifân olur” buyurdu. Birgün yine oradan geçiyordu. “Şimdi o güzel koku daha çok geliyor. Ümîd ederim ki, o büyük insan dünyâya gelmiştir” buyurdu. Böyle buyurduğu zaman, Behâüddîn -i Buh ârî hazretleri doğalı üç gün olmuştu. Dedesi, çocuğun göğsünün üzerine hediye koyup, Muhammed Bâbâ Semmâsî’ye getirince; “Bu bizim oğlumuzdur. Biz bunu kabûl eyledik” buyurup, talebelerine de; “Kokusunu aldığım işte bu çocuktur. Zamanının rehberi ve bir ta nesi olacaktır” buyurdu. Sonra halîfesi Emîr Külâl hazretlerine, bu çocuğun iyi yetiştirilmesini tehbîh etti.",
    portre: null
  },
  {
    id: 15,
    ad: "Hazret-i Seyyid Emîr Külâl",
    tam_ad: "Hazret-i Seyyid Emîr Külâl (kuddise sirruh)",
    lakap: "Emîr-i Buhârâ",
    asir: "XIV. Yüzyıl",
    dogum: "~1312", vefat: "1370",
    sehir: "Suhâre (Buhara yakını)", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [39.7500, 64.5000],
    biyografi: "Hazret-i Muhammed Bahâeddin Şâh Nakşibend'in (kuddise sirruh) hakiki ve baş mürşididir. Seyyid soyundan gelen bu büyük zât, hem ilim hem de manevi nüfuz bakımından döneminin en seçkin şahsiyetlerindendi. Buhara'ya bağlı Suhâre köyünde yaşamış ve orada medfundur.\n\nEvliyânın büyüklerinden, insanları Hakka da’vet eden, doğru yolu göstererek saadete kavuşturan ve kendilerine “Silsile -i âliyye” denilen büyük âlim ve velîlerin ondördüncüsüdür. Hazreti Hüseyn’in soyundan olup, seyyiddir. Evliyânın meşhûrlarından olan Muhammed Bâbâ Semmâsî’nin talebesi ve Behâeddîn -i Buhârî Nakşibend hazretlerinin hocasıdır. Çömlekçilik yaptığı için “Külâl” ismiyle meşhûr olmuştur. Buhârâ’nın Sûhârî kasabasında doğdu. Doğum târihi bilinmemektedir. 772 (m. 1370) senesinde Sûhârî’de vefât etti. Kabri oradadır. Büyük bir âlim ve mürşid -i kâmil olup, her ânını İslâmiyete uygun olarak geçirirdi. Pekçok kimse onun sohbetinde ve derslerinde kemâle ulaşmıştır. Onun üstün hâllerini gösteren çok menkıbesi vardır. Annesi şöyle anlatmıştır: “Emîr Külâl’e hâmile iken, şüpheli bir lokma yesem, karın ağrısına tutulurdum. O lokmayı mi’demden geri çıkarmadıkça, karın ağrısından kurtulamazdım. Bu hâl üç defa başıma gelince, çok temiz ve hayırlı bir çocuğa hâmile olduğumu a nladım. Bunun üzerine yediğim lokmaların helâlden olmasına çok dikkat edip, ihtiyâtlı davrandım.” Babası Seyyid Hamza, Medine’den gelip, Buhârâ’nın Efşene köyüne yerleşmişti Sâlih bir zât idi. Bir defasında, zamanın en meşhûr evliyâsı Seyyid Atâ, yanında zamânın meşhûr zâtlarıyla büyük bir cemâat hâlinde, Emîr Külâl hazretlerinin babası Seyyid Hamza’nı n bulunduğu köyden geçiyordu. Bu yolculuğu sırasında tanışıp dost oldular. Bundan sonra Seyyid Atâ’nın her ne zaman oraya yolu düşse, önce doğruca Seyyid Hamza’nın evine gider, başkalarıyla daha sonra görüşürdü. Yine bir defasında Efşene köyüne uğramış ve Seyyid Hamza’nın yanına gelmişti. Bu gelişinde ona bir müjde verip, şöyle demiştir: “Ey Kardeşim! Allahü teâlâ sana öyle bir evlât verecek ki, şânı pek yüce olacak.",
    portre: null
  },
  {
    id: 16,
    ad: "Hazret-i Muhammed Bahâeddin Nakşibend",
    tam_ad: "Hazret-i Muhammed Bahâeddin Şâh Nakşibend (kuddise sirruh)",
    lakap: "Şâh-ı Nakşibend",
    asir: "XIV. Yüzyıl",
    dogum: "1318", vefat: "1389",
    sehir: "Kasr-ı Ârifân (Buhara yakını)", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [39.7744, 64.4325],
    biyografi: "Bu mübarek silsilenin adını taşıyan büyük velî ve Nakşibendiyye tarikatının kurucu imamıdır. 'Dilde Hak, elde halk' ve 'Halvet der encümen' prensiplerini hayatında mükemmel surette yaşamıştır. Hafi zikri esas almış, kalp ile zikrin ehemmiyetini öğretmiştir. Türbesi Buhara yakınındaki Kasr-ı Ârifân'dadır ve dünyanın dört bir yanından gelen hacı adayları ziyaret eder.\n\nEvliyânın büyüklerinden ve müslümanların gözbebeği olan yüksek âlimlerden. İnsanları Hakka da’vet eden, doğru yolu göstererek saadete kavuşturan ve kendilerine “Silsile-i âliyye” denilen büyük âlim ve velîlerin onbeşincisidir. Muhammed Bâbâ Semmâsî’nin ve Emîr Külâl’in talebesidir. İsmi, Muhammed bin Muhammed’dir. Bahâeddîn ve Şâh-ı Nakşibend gibi lakabları vardır. Allahü teâlânın sevgisini kalblere nakşettiği için, “Nakşibend” denilmiştir. Seyyid olup, soyu şöyledir: Babası Seyyid Muhammed Buhârî, onun bab ası Seyyid Muhammed Celâl Burhâneddîn, onun babası Seyyid Abdullah, onun babası Zeynel’âbidîn, onun babası, Seyyid Kâsım, onun babası Seyyid Şa’bân, onun babası Seyyid Burhâneddîn, onun babası Seyyid Tâkî, onun babası İmâm -ı Mûsâ Kâzım, onun babası İmâm -ı Ca’fer-i Sâdık hazretleridir. Behâüddîn Şâh -ı Nakşîbend hazretleri, 718 (m. 1318) senesinde Buhârâ’ya beş kilometre kadar uzakta bulunan Kasr-ı ârifân’da doğdu. 791 (m. 1389)’de Kasr -ı ârifân’da Rebî’ul-evvel ayının üçüncü günü olan Pazartesi günü vefât et ti. Kabri oradadır, İslâm âlimlerinin en meşhûrlarından olup, tasavvufda en yüksek derecelere ulaşmıştır. Hem zamanında, hem de kendinden sonraki asırlarda onun sebebi ile pekçok insan hidâyete kavuşmuştur. Zamanının büyük evliyâsı olan Muhammed Bâbâ Semmâsî, henüz o doğmadan, doğduğu yer olan Kasr-ı ârifân’a gelmişti. Bu gelişinde, burada bir büyük zâtın kokusu geliyor. Bu beldede büyük bir evliyâ yetişecek diyerek işâret etmiş, tarikatın İmâmı olacak emsals iz bir zâtın buradan zuhur edeceğini talebelerine ve sevenlerine müjdelemişti. Babası şöyle anlatmıştır: “Oğlum Bahâeddîn’in doğmasından üç gün sonra, Hâce Muhammed Bâbâ Semmâsî hazretleri, bütün talebeleri ile Kasr -ı ârifân’a gelmişti. Ben onu çok sever v e muhabbet beslerdim.",
    portre: null
  },
  {
    id: 17,
    ad: "Hazret-i Alâeddin-i Attâr",
    tam_ad: "Hazret-i Alâeddin-i Attâr (kuddise sirruh)",
    lakap: "Hvâce Alâeddin",
    asir: "XIV–XV. Yüzyıl",
    dogum: "~1340", vefat: "1400",
    sehir: "Cağânyân (Termiz yakını)", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [37.2000, 67.3000],
    biyografi: "Hazret-i Muhammed Bahâeddin Şâh Nakşibend'in (kuddise sirruh) hem en yakın halifesi hem de damadıdır. Bu mübarek emanetin manevi varisi sıfatıyla silsileyi sonraki nesle taşımıştır. Termiz civarındaki Cağânyân bölgesinde medfundur.\n\nBuhârâ’da yetişen evliyânın en büyüklerinden. İnsanları Hakka da’vet eden, onlara doğru yolu gösterip hakîkî saadete kavuşturan ve kendilerine “Silsile -i âliyye” denilen büyük âlim ve velîlerin onaltıncısıdır. İsmi, Muhammed bin Muhammed Buhârî’dir. Muhamm ed Behâeddîn-i Buhârî hazretlerinin dâmâdı ve talebesidir. Zamanının kutb -i irşâdı idi. Zamanında herkese rüşd ve îmân onun vâsıtası ile gelir, İslâmiyeti korurdu. Onun varlığı ile, dîn -i İslâm başı boş kalmadı, din düşmanları pervasızca, dîni yıkmağa ve d eğiştirmeğe kalkışamadı. Hakkında, Seyyid Şerîf Cürcânî; “Alâüddîn -i Attâr hazretlerinin sohbetine kavuşunca, Rabbimi tanıyabildim” dedi. Buhârâ’nın Cağanyân nahiyesinde 802 (m. 1400)’de vefât etti. Alâüddîn-i Attâr’ın babası, Buhârâ’nın zengin eşrafından idi. Üç oğlu vardı. Bunlardan büyük oğullarının isimleri; Sehâbeddîn ve Hâce Mübârek’tir. Alâüddîn en küçükleri idi. Babası vefât edince, oğullarına çok fazla mal kaldı. Fakat Alâüddîn, mirastan hiç kabûl etmeyip, Şâh -ı Nakşibend Muhammed Behâeddîn-i Buhârî’ye talebe olmayı tercih etti. Huzûrlarına varıp hâlini arz etti ve talebeliğe kabûl buyurulmasını istirhâm eyledi. O da; “Bugün bir tepsi elma alıp, kardeşlerinin mahallesinde sat” buyurdu. Alâüddî n, soylu ve tanınmış bir aileye mensûp olmasına rağmen, kibirlenmeyerek, kardeşlerinin mahallesinde, hiç kimsenin sözlerine aldırış etmeden, o gün bağırarak elma sattı. Ertesi gün Şâh -ı Nakşibend’in huzûruna gelerek; “Emîrlerinizi yerine getirmeye çalıştım efendim” dedi. Behâeddîn -i Buhârî; “Bugün de kardeşlerinin dükkânı önünde satacaksın” buyurdu. Alâüddîn; “Peki efendim!” diyerek, ağabeylerinin dükkânı önünde bağırarak elma satmaya başladı. Ağabeyleri yanına gelip; “Bizi elâleme rezîl etme, para lâzım is e, istediğin kadar verelim” dediler.",
    portre: null
  },
  {
    id: 18,
    ad: "Hazret-i Yakûb-ı Çerhî",
    tam_ad: "Hazret-i Yakûb-ı Çerhî (kuddise sirruh)",
    lakap: "Hvâce Yakûb",
    asir: "XV. Yüzyıl",
    dogum: "~1359", vefat: "1447",
    sehir: "Hisar", ulke: "Tacikistan", bolge: "Mâverâünnehr",
    koordinat: [38.5236, 68.7786],
    biyografi: "Hazret-i Alâeddin-i Attâr (kuddise sirruh)'ın önde gelen halifesidir. Tacikistan'ın Hisar şehrinde uzun yıllar ikamet etmiş ve orada medfundur. İlim, zühd ve derin takvası sayesinde büyük saygınlık kazanmıştır.\n\nEvliyânın büyüklerinden. İnsanların i’tikâd, amel, ibâdet ve ahlâk husûsunda doğruyu öğrenip yapmalarını sağlayan ve Allahü teâlânın rızâsına kavuşturmak için rehberlik eden ve kendilerine “Silsile-i âliyye” denilen İslâm âlimlerinin onyedincisidir. İsmi, Ya’kûb bin Osman bin Mahmûd’dur. Gazne’de Cerh köyünde doğdu, doğum târihi bilinmemektedir. 851 (m. 1447) senesinde Hülfetû’da vefât etti. Burası, sınır köylerinden bir köy olup, kabri oradadır. Derin âlim ve veliyyi kâmil idi. Ya’kûb-i Çerhî, önce Hirat’a gidip, bir müddet ilim tahsili yaptı. Sonra yine ilim tahsili için Mısır’a gitti. Orada Zeynüddîn Hafi ile birlikte, zamanının büyük âlimi Mevlânâ Şihâbüddîn Şhrvânî’den ve diğer âlimlerden aklî ve naklî ilimleri öğrendi. Sonra Buhârâ’ya gitti. Orada da â limlerden ilim öğrenip, icâzet aldı. Zâhirî ilimlerde yetişdikten sonra tasavvuf ilmine yöneldi. Tasavvuf ilminde ve hâllerinde önce Şâh -ı Naksihcnd Behâeddîn -i Buhârî’nin, sonra da onun halîfesi Alâüddîn-i Attâr’ın sohbetinde yetişti. Kendisi şöyle anlatmıştır: “Buhârâ’nın âlimlerinden ilim tahsil edip icâzet aldıktan sonra memleketime dönmek üzere idim. İçimde Behâeddîn -i Buhârî hazretlerinin yanına gitmek arzusu hâsıl oldu. Huzûruna varıp; “Beni hatırdan çıkarmayımz” diye yalvardım. “ Tam gideceğin sırada mı bana geliyorsun?” buyurdu. “Gönlüm iştiyâkınızla dolu, sizi seviyorum” dedim. “Bu arzu ne sebepten geliyor?” dedi. “Büyük bir zâtsınız ve herkesin makbûlüsünüz” dedim. Bunun üzerine; “Bu sebep kâfi değil, daha makbûl birşey bulman lâzımdır. Halkın beni kabûlü şeytanî olabilir” buyurdu.",
    portre: null
  },
  {
    id: 19,
    ad: "Hazret-i Ubeydullah Ahrâr",
    tam_ad: "Hazret-i Ubeydullah Ahrâr (kuddise sirruh)",
    lakap: "Hvâce Ahrâr",
    asir: "XV. Yüzyıl",
    dogum: "1404", vefat: "1490",
    sehir: "Semerkand", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [39.6542, 66.9597],
    biyografi: "Silsilenin Orta Asya'daki en güçlü halkalarından birini oluşturan bu büyük zât, Semerkand çevresinde hem manevi hem siyasi büyük nüfuz sahibi olmuştur. Timurlu hükümdarlarını ve devlet adamlarını irşat etmiş; döneminin siyasi hayatında İslam'ın hakkını korumuştur. Türbesi Semerkand yakınındadır.\n\nEvliyânın büyüklerinden. İnsanların i’tikâd, ibâdet ve ahlâk husûsunda doğruyu öğrenip yapmalarını sağlayan ve Allahü teâlânın rızâsına kavuşturmak için rehberlik eden ve kendilerine “Silsile -i âliyye” denilen İslâm âlimlerinin onsekizincisidir. İsmi, Ubey dullah bin Mahmûd bin Şihâbüddîn’dir. 806 (m. 1403)’da Taşkend’de doğdu. 895 (m. 1490) senesinde Semerkand’da vefât etti. Babası, o zamanın büyük âlimlerinden evliyâ bir zât idi. Annesi ise Hazreti Ömer’in soyundandır. Ubeydüllah-i Ahrâr hazretleri doğduğunda, kırk gün annesini emmemiştir. Annesi nifasdan temizlendikten sonra emmeye başlamıştır. Daha çocuk iken yüzünde öyle bir nûr parlardı ki, görenler hayran kalıp, ona duâ ederlerdi. Dilinden Allahü teâlânın ismi hiç d üşmez, devamlı zikir ile meşgûl olurdu. Dedesi Hâce Şihâbüddîn, âlim ve evliyâ bir zât idi. Vefât edeceği sırada, torunlarını son olarak görüp vedalaşmak istedi ve onlarla tek tek vedâlaştı. Torunu Ubeydüllah- i Ahrâr’ı da görmek isteyip, babasına onu getirmesini söyledi. Yanına getirdiklerinde o zaman çok küçüktü. O yanına getirilince, beni yatağımdan kaldırın deyip, yatağı üzerinde oturarak, Ubeydüllah-i Ahrâr’ı kucağına aldı. Sarılarak ağladı ve şöyle dedi: “Benim istediğim çocuk budur. Ben, bunun büyük b ir zât olduğu zaman hayatta olmam. Bunun âlemdeki tasarrufunu ve yaptığı hizmetleri göremem. Bu çocuğun şânı âlemi tutacak, İslâmiyete hizmet edecektir. Cihan pâdişâhları bunun emrine itaat edecekler. Bundan zuhur edecek işler, önceki âlimlerden zuhur etme miştir.” Daha birçok müjdeler verdikten sonra, tekrar bağrına basıp sarılarak, Ubeydüllah-i Ahrâr’ın babası Mahmûd Şâşî’ye; “Benim bu oğlumu iyi gözet, gerektiği gibi yetiştirip terbiye et” diyerek vasıyyet etti.",
    portre: null
  },
  {
    id: 20,
    ad: "Hazret-i Muhammed Zâhid",
    tam_ad: "Hazret-i Muhammed Zâhid (kuddise sirruh)",
    lakap: "Hvâce Muhammed",
    asir: "XV–XVI. Yüzyıl",
    dogum: "?", vefat: "1529",
    sehir: "Semerkand", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [39.7000, 66.8000],
    biyografi: "Hazret-i Ubeydullah Ahrâr (kuddise sirruh)'ın en değerli halifelerindendir. Semerkand bölgesinde talebe yetiştirmiş ve mübarek silsileyi sonraki nesle büyük bir sadakatle aktarmıştır. Zühd ve takvasıyla tanınan bu büyük velî Mâverâünnehr'de medfundur.\n\nEvliyânın büyüklerinden, insanları Hakka da’vet eden, doğru yolu göstererek saadete kavuşturan ve “Silsile-i âliyye” denilen büyük âlim ve velîlerin ondokuzuncusudur. Semerkandlı olup, doğum târihi bilinmemektedir. 936 (m. 1529) senesinde Semerkand’a bağlı Hisâr’ın Vahş köyünde vefât etti. Kabr-i şerîfi oradadır. Kâdı Muhammed Zâhid Semerkandî, silsile -i âliyye büyüklerinden olan Ya’kûb -ı Çerhî hazretlerinin kızının oğlu olup, torunudur. Hocası, her ilimde söz sahibi Ubeydüllah-i Ahrâr’dır. Bu hocasının sohbetine kavuşmadan önce, çok gayretler sarfedip, nefs mücâhe desi yaptı. Nefsini ıslâh etmek için uğraştı. Bu hâli yıllarca sürdü. Daha sonra Ubeydüllah -i Ahrâr’a 883 (m. 1429) senesinde talebe oldu. Oniki sene sohbetinde ve hizmetinde bulundu. Ondan feyz alarak kemâle erdi. Vefâtından sonra da yerine irşâd makamına geçip, insanlara feyz vermek üzere halîfesi oldu. Kâdı Muhammed Zâhid, “Silsilet-ül-ârifîn” adlı eserinde, Ubeydüllah-i Ahrâr hazretlerine talebe olmasını şöyle anlatmıştır: “Hocama talebe oluşum şöyle vukû’ bulmuştu: Şeyh Ni’metullah adında bir ilim talebesi ile Semerkand’dan Hirat’a ilim öğrenmek için y ola çıkmıştık. Şâdmân köyüne varınca, havanın çok sıcak olması sebebiyle, günlerce o köyde kaldık. Biz burada iken, Ubeydüllah-i Ahrâr bu köye teşrîf etti. Bir ikindi vakti ziyâretine gittik. Bana; “Sen neredensin?” dedi. “Semerkand’danım” dedim. Sonra sohbete başladı. Çok güzel konuşuyordu. Konuşması sırasında benim kalbimden ve hatırımdan geçen şeyleri bir bir saydı. Hirat’a gitmek için yola çıkmamın sebebini de söyledi. Bunun üzerine kalbim ona tamamen tutuldu. Sonra bana dedi ki: “Eğer maksadın ilim öğrenmekse, o iş burada kolaydır.” iyice anladım ve kanâat getirdim ki, benim hatırımdan geçen şeyleri biliyordu.",
    portre: null
  },
  {
    id: 21,
    ad: "Hazret-i Derviş Muhammed",
    tam_ad: "Hazret-i Derviş Muhammed (kuddise sirruh)",
    lakap: "Derviş Hvâce",
    asir: "XVI. Yüzyıl",
    dogum: "?", vefat: "1562",
    sehir: "Semerkand bölgesi", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [39.5000, 66.5000],
    biyografi: "Hazret-i Muhammed Zâhid (kuddise sirruh)'in halifesi ve bu mübarek silsilenin söz konusu dönemdeki taşıyıcısıdır. Orta Asya'da manevi irşat geleneğini büyük bir titizlikle sürdürmüş ve emaneti kâmil surette aktarmıştır.\n\nEvliyânın büyüklerinden. İnsanları Hakka da’vet eden, doğru yolu göstererek saadete kavuşturan ve kendilerine “Silsile-i âliyye” denilen büyük âlim ve velîlerin yirmincisidir. Doğum târihi bilinmemekte olup, 970 (m. 1562) senesinde vefât etti. Rûh ilimlerinde mütehassıs idi. Büyük âlim ve kâmil bir velî olan dayısı Kâdı Muhammed Zâhid’den ders alarak yetişti. Dayısına talebe olmadan önce, onbeş sene nefsinin isteklerinden kurtulmak için mücâdele etmiş ve insanlardan uzak yaşamıştı. Birgün ellerini açıp, acizliğini ve çaresizliğini Allahü teâlâya yalvararak arz etmişti. Aniden Hızır aleyhisselâm gelip; “Eğer sabır ve kanâat istiyorsan, Muhammed Zâhid’in hizmet ve sohbetine kavuşmakta acele et. O sana sabır ve kanâati öğretir” buyurdu. Hemen Muhammed Zâhid’in yüksek huzûruna varıp, orada ilim tahsil etti. Güzel terbiye görüp, kemâle geldi. Hocasının vefâtından sonra yerine geçip, Semerkand’da, doğru yoldan ayrılanlarla ve dîne sonradan sokulan bid’atlerle uğraştı. Bid’atleri yok etti. Çok velî yetiştirdi. İnsanları Allahü teâlânın yoluna çağırmada çok gayret gösterdi. Talebelerinin terbiyesi husûsunda, insanüstü bir kuvvet ve gayrete sahipti. 970 (m. 1562) senesinde, ikinci binin yenileyicisi İmâm -ı Rabbânî hazretlerinin dünyâya gelmesinden bir sene önce, B üster kasabasının Dasferar köyünde vefât etti. İnsanları irşâd için yetiştirdiği yüksek talebeleri pekçok olup, en büyüğü oğlu Hâce Muhammed İmkenegî’dir. 1) Tam İlmihâl Se’âdet-i Ebediyye sh. 997 2) Umdet-ül-makâmât sh. 75 3) Hadâik-ül-verdiyye sh. 177 4) Reşehât zeyli sh. 5 5) Hadikât-ül-n’liyâ sh. 88 6) Behçet-üs-seniyye sh. 8 7) İrgam-ül-merid sh. 67",
    portre: null
  },
  {
    id: 22,
    ad: "Hazret-i Hâce Emkinegî",
    tam_ad: "Hazret-i Muhammed Emkinegî (kuddise sirruh)",
    lakap: "Hvâce Emkine",
    asir: "XVI. Yüzyıl",
    dogum: "~1519", vefat: "1600",
    sehir: "Emkine (Buhara yakını)", ulke: "Özbekistan", bolge: "Mâverâünnehr",
    koordinat: [39.9000, 64.2000],
    biyografi: "Buhara yakınlarındaki Emkine köyünden büyük velîdir. Hazret-i Derviş Muhammed (kuddise sirruh)'den aldığı mübarek emaneti titizlikle korumuş; halifesi Hazret-i Muhammed Bâkibillâh (kuddise sirruh) aracılığıyla bu nurlu silsileyi Hindistan coğrafyasına taşıtmıştır.\n\nEvliyânın büyüklerinden. İnsanları Hakka da’vet eden; doğru yolu göstererek, saadete kavuşturan ve kendilerine “Silsile-i âliyye” denilen büyük âlim ve velîlerin yirmibirincisidir. 918 (m. 1512) senesinde Buhârâ’nın İmkene kasabasında doğdu. 1008 (m. 1599) ’de doksan yaşında iken İmkene’de vefât etti. Evliyâ’nın büyüklerinden Derviş Muhammed hazretlerinin oğlu ve Muhammed Bâkî -billah hazretlerinin hocasıdır. Zâhirî ve bâtınî ilimleri babasından öğrendi. Babasından feyz alarak tasavvufda yetişip kemâle erdi. Rûh ilimlerinin mütehassısı idi. Bütün ömrü; İslâmiyete hizmetle ve Peygamberimizin ( aleyhisselâm ) güzel ahlâkını insanlara duyurmakla ve öğretmekle geçti. Çok velî yetiştirdi. Yetiştirdiği velî zâtlardan en başta gelen talebesi, kendisinden sonra halîfesi olan Muhammed Bâkî-billah’dır. Muhammed Bâkî -billah bir gece rü’yâsında Hâcegî Muhammed İmkenegî hazretlerini, gördü. Ona; “Ey oğul! Senin yolunu gözlüyorum” buyurdu. Bâkî -billah hazretleri buna çok sevindi. Hemen huzûruna gitti. Huzûruna varınca ona çok iltifât ve inâyet gösterip, yüksek hâllerini dinledi. Sonra üç gün üç gece birlikte bir odada başbaşa kalıp, sohbet ettiler. Hâcegî hazretleri ona feyz verip, yüksek fâidelere k avuşturdu. Sonra Bâkî-billah hazretlerine; “Sizin işiniz, Allahü teâlânın yardımı ve bu yüksek yolun büyüklerinin rûhlarının terbiyeleri ile tamâm oldu. Tekrar Hindistan’a gitmeniz îcâb ediyor. Çünkü bu silsile -i âliyyenin, orada sizin sayenizde parlıyacağını görüyorum. Bereket ve terbiyenizden çok istifâde edip, büyük işler yapacak olanlar gelecek” buyurdu. Hâce Bâkî-billah (kuddise sirruh) kendilerini bu işe lâyık görmediğinden, özür dilediyse de, Hâcegî İmkenegî, ona istihâre yapmasını emretti.",
    portre: null
  },
  {
    id: 23,
    ad: "Hazret-i Muhammed Bâkibillâh",
    tam_ad: "Hazret-i Muhammed Bâkibillâh (kuddise sirruh)",
    lakap: "Bâkibillâh",
    asir: "XVI–XVII. Yüzyıl",
    dogum: "1564", vefat: "1603",
    sehir: "Delhi", ulke: "Hindistan", bolge: "Hindistan",
    koordinat: [28.6139, 77.2090],
    biyografi: "Nakşibendiyye'yi Hindistan'a taşıyan ilk büyük mürşiddir. Semerkand'da tahsil ettiği manevi mirası Delhi'ye getirmiş; halifesi Hazret-i Ahmed Fârûk Serhendî İmâm-ı Rabbânî (kuddise sirruh) aracılığıyla tüm dünyaya yaymıştır. Delhi'de medfundur.\n\nEvliyânın büyüklerinden, insanları Hakka da’vet eden, doğru yolu göstererek saadete kavuşturan ve kendilerine “Silsile-i aliyye” denilen büyük âlim ve velîlerin yirmiikincisidir. İkinci bin yılının müceddidi ve İslâm âlimlerinin gözbebeği olan İmâm -ı Rabbânî Ahmed -i Fârûkî Serhendî hazretlerinin hocasıdır. Babasının ismi Abdüsselâm olup, faziletli bir zât idi. Annesi ise Hazreti Hüseynin soyundan olup, seyyide ve mübârek bir hanım idi. Muhammed Bâkî-billah hazretleri, 971 (m. 1563) senesinde Kabil şehrinde doğdu. 10 12 (m. 1603)’de Delhi’de kırk yaşında iken vefât etti. Türbesi, Kutabrol denilen yerdeki kendi mescidinin yanında olup ziyâret edilmektedir. Muhammed Bâkî-billah’ın büyüklük hâli daha çocukluk zamanlarında simasından belli olurdu. Yüksek bir zât olacağının işâretleri ve büyük fâidelere sebep olacağının alâmetleri, işlerinden, çalışmalarından ve gayretinden anlaşılırdı. Daha çocukluk zamanlarınd a, ba’zen bütün gün odanın bir köşesinde başını önüne eğip sessizce oturur, tefekküre dalardı. Gençliğinde, ilim tahsili için Kabil’den Semerkand’a gidip, zâhirî ve aklî ilimleri, zamanının en büyük âlimlerinden olan Mevlânâ Sâdık -ı Hulvânî’den öğrendi. Yü ksek yaradılışı ve kabiliyeti ile kısa zamanda, hocasının talebeleri arasında en yüksek seviyeye ulaştı. Zâhirî ilimleri öğrenip bitirmeden tasavvufa yönelip, bâtını ilimleri öğrenmek için, bu yolun büyük âlimlerinin sohbetlerine ve derslerine gitti. Yaratılışındaki zekâsının ve kabiliyetinin üstünlüğü ile, ilimlerde yüksek bir dereceye ulaştı. Sâlih ve doğru sözlü bir zât şöyle anlatmıştır: “Hâce Muhammed Bâkî-billah, aklî ilimleri bırakıp, tasavvufa yöneldiği ilk zamanlarda, büyük zâtlardan birinin huzûruna gitmişti.",
    portre: null
  },
  {
    id: 24,
    ad: "Hazret-i Ahmed Fârûk Serhendî",
    tam_ad: "Hazret-i Ahmed Fârûk Serhendî İmâm-ı Rabbânî (kuddise sirruh)",
    lakap: "İmâm-ı Rabbânî, Müceddid-i Elf-i Sânî",
    asir: "XVI–XVII. Yüzyıl",
    dogum: "1564", vefat: "1624",
    sehir: "Serhend", ulke: "Hindistan", bolge: "Hindistan",
    koordinat: [30.6341, 76.3953],
    biyografi: "'İkinci Binin Müceddidi' lakabını almış büyük alim ve velîdir. Mektûbât adlı eseri İslam tasavvuf literatürünün en değerli kaynakları arasında kabul edilmektedir. Hint Müslümanlarının İslami kimliğini muhafaza etmesinde ve Nakşibendî geleneğinin yeniden ihyasında tarihi bir rol üstlenmiştir. Serhend'de medfundur.\n\nHindistan’da yetişen meşhûr İslâm âlimi ve büyük velî. Âriflerin ışığı, velîlerin önderi, İslâmın bekçisi, müslümanların baştâcı, müceddid, müctehid ve İslâm âlimlerinin gözbebeğidir, insanların i’tikâd, ibâdet ve ahlâk husûsunda doğruyu öğrenmelerini, öğrendikleri bu bilgiler ile amel etmelerini sağlayan, insanları Allahü teâlânın rızâsına kavuşturmak için rehberlik eden ve kendilerine “Silsile -i âliyye” denilen İslâm âlimlerinin yirmiüçüncüsüdür. İsmi, Ahmed bin Abdülehad bin Zeynel’âbidîn’dir. Lakabı Bedreddîn, künyesi Ebü’l-Berekât’dır. 971 (m. 1563) senesinde Hindistan’ın Serhend (Sihrind) şehrinde doğdu. 1035 (m. 1624)’de Serhend’de 63 yaşında iken vefât etti. Türbesi oradadır. İmâm-ı Rabbânî ismiyle tanınmıştır, İmâm-ı Rabbânî, Rabbânî âlim demektir. Rabbânî âlim de; kendisine ilim ve hikmet verilmiş, ilmi ile amel eden, ilim ve amel bakımından kâmil olan âlim demektir. Hicri ikinci bin yılının Müceddidi olmasından dolayı “Müceddîd-i elf-i sânî”, ahkâmı İslâmiye ile tasavvufu vasletmesinden, birleştirmesinden dolayı da, “Sıla” ismi verilmiştir. Hazreti Ömer’in soyundan olduğu için, “Fârûkî” nesebiyle anılmış, Serhend şehrinden olduğu için de oraya nisbetle, “Serhendî” nisbeti verilmiştir. Bütün bu vasıflarıyla birlikte ismi, İmâm -ı Rabbânî, Müceddîd -i e lf-i sânî, Şeyh Ahmed -i Fârûkî Serhendî’dir (kuddise sirruh). İmâm-ı Rabbânî hazretleri, Peygamberimizin ( aleyhisselâm ) hadîs -i şerîfde; “Benden sonra peygamber gelseydi, Ömer bin Hattâb peygamber olurdu.” buyurarak methettiği ve Hazreti Ebû Bekr’den sonra insanların en üstünü olan Hazreti Ömer’in soyundan olup, yi rmidokuzuncu torunudur.",
    portre: null
  },
  {
    id: 25,
    ad: "Hazret-i Muhammed Mâsum",
    tam_ad: "Hazret-i Muhammed Mâsum (kuddise sirruh)",
    lakap: "Mâsum-ı Fârûkî",
    asir: "XVII. Yüzyıl",
    dogum: "1599", vefat: "1668",
    sehir: "Serhend", ulke: "Hindistan", bolge: "Hindistan",
    koordinat: [30.6400, 76.4000],
    biyografi: "Hazret-i Ahmed Fârûk Serhendî İmâm-ı Rabbânî (kuddise sirruh)'nin üçüncü oğlu ve en önde gelen halifesidir. Babasından aldığı manevi mirası özümseyerek Hindistan, Orta Asya ve Osmanlı topraklarına yaymıştır. Çeşitli mektup ve eserleri günümüze ulaşmıştır.\n\nEvliyânın meşhûrlarından, büyük İslâm âlimi. Hicri ikinci bin yılının müceddidi. İmâm-ı Rabbânî hazretlerinin üçüncü oğludur. İnsanları Hakka da’vet eden, doğru yolu göstererek saâdete kavuşturan ve kendilerine; “Silsile-i aliyye” denilen büyük âlim ve velîlerin yirmidördüncüsüdür. Lakabı Mecdüddîn olup, “Urvet -ül-vüskâ” ismiyle meşhûrdur. Urvet -ül-vüskâ; sağlam ip, kendisine uyulan büyük âlim demektir. 1007 (m. 1599) senesinde Hindistan’ın Serhend şehrine iki mil uzakta bulunan Mülk-i Haydar mevkiinde doğdu. 1079 (m. 1668) senesinde Serhend’de vefât etti. Türbesi, mübârek babası İmâm -ı Rabbânî hazretlerinin türbesinin birkaç yüz metre kuzeyindedir. Muhammed Ma’sûm hazretleri, bu ümmette gelmiş olan en yüksek evliyâdandır. O doğduğu zaman babası; “Muhammed Ma’sûm’un dünyâya gelişi, bizim için çok bereketli ve pek mübârek oldu. Onun doğmasından bir kaç ay sonra yüksek hocamın (Muhammed Bâkî - billah’ın) huzûruna kavuştum (Ona talebe oldum). Gördüklerimi orada gördüm” buyurmuştur. Daha üç yaşında iken, tevhîd kelimesini söylerdi. Kur’ân-ı kerîmi üç ayda ezberledi, İlim tahsil ettiği sırada, onbir yaşında iken, zikr ve murâkabe yolunu babasından aldı. İmâm -ı Rabbânî hazretleri onun hakkında; “Muhammed Ma’sûm’un günbegün, anbean bizim nisbetimizi elde etme hâli; dedesinin yazdığı Vikâye kitabını, o yazdıkça arkasından ezberleyen “Şerhi Mevâkıf” kitabının sahibinin hâline benzer” buyurdu. Tasavvufda yetişmesi ve makamları aşması pek sür’atli oldu. Hâllere, yüksek makamlara, eşsiz varidata ve kemâllere kavuşunca, mübârek babası kendisine mutlak icâzet verdi. Babasını, zâhir ve bâtın ilimlerinde adım adım ta’kib etti.",
    portre: null
  },
  {
    id: 26,
    ad: "Hazret-i Seyfeddin Fârûkî",
    tam_ad: "Hazret-i Seyfeddin Fârûkî (kuddise sirruh)",
    lakap: "Seyfeddin-i Serhendî",
    asir: "XVII. Yüzyıl",
    dogum: "~1640", vefat: "1718",
    sehir: "Serhend", ulke: "Hindistan", bolge: "Hindistan",
    koordinat: [30.6341, 76.3953],
    biyografi: "Hazret-i Muhammed Mâsum (kuddise sirruh)'un oğlu ve önde gelen halifesidir. Hazret-i İmâm-ı Rabbânî (kuddise sirruh) sülalesinin bu mübarek halkasında ilim ve maneviyat bir arada akmaktadır. Serhend'de medfundur.\n\nEvliyânın büyüklerinden. İnsanların i’tikâd, ibâdet ve ahlâk husûsunda doğruyu öğrenmelerini ve öğrendikleri bu bilgiler ile amel etmelerini sağlayan, insanları Allahü teâlânın rızâsına kavuşturmak için rehberlik eden ve kendilerine silsile -i aliyye denile n İslâm âlimlerinin yirmibeşincisidir. İkinci bin yılının müceddidi olan İmâm-ı Rabbânî hazretlerinin torunu, Urvet- ül-vüskâ Muhammed Ma’sûm -ı Fârûkî’nin beşinci oğludur. Muhammed Ma’sûm -i Fârûkî hazretlerinin altı oğlu olup, hepsi de kemâle ermiş Vilâyet -i hâssa -i Muhammediyye ile şereflenmişlerdir. Beşinci oğlu Muhammed Seyfeddîn (r.aleyh) de tasavvuf bilgilerinin mütehassısı idi. “Muhyissünne” adı ile meşhûr oldu. 1049 (m. 1639) senesinde Serhend’de doğdu. 1098 (m. 1696) senesinde yine Serhend’de vefât etti. Kabri mübârek babasının medfûn bulunduğu türbenin birkaçyüz metre güneyindeki türbededir. Boyu uzun, yüzü esmer ve heybetli, gözleri büyükçe, sakalının iki tarafı az seyrek idi. Zâhir ve bâtın ilimlerinde çok yüksek olan Muhammed Seyfeddîn -i Fârûkî hazretlerinin doğumundan i’tibâren büyük bir zât olacağı ve insanlara hidâyet rehberi olacağı belliydi. Nakledilir ki: Doğum zamanında bir melek görünüp; “Doğduğu gün, öldüğü gün ve tekrar dirildiği gün Allah’ın selâmı üzerine olsun” meâlindeki, Meryem sûresi 15. âyet-i kerîmeyi okuyarak müjde vermişti. İlim, irfan kaynağı ve kerâmetler sahibi Seyfeddîn-i Fârûkî hazretleri, küçük yaşından i’tibâren ilme yönelip ders okuyabilecek yaşa geldiği zaman, Kur’ân-ı kerîmi ezberledi. Sonra da amcası Muhammed Sa’îd’den aklî ve naklî ilimleri tahsil edip kısa zamand a çok şeyler öğrendi.",
    portre: null
  },
  {
    id: 27,
    ad: "Hazret-i Nur Muhammed Bedâyûnî",
    tam_ad: "Hazret-i Nur Muhammed Bedâyûnî (kuddise sirruh)",
    lakap: "Şeyh Nur Muhammed",
    asir: "XVII–XVIII. Yüzyıl",
    dogum: "~1664", vefat: "1722",
    sehir: "Bedâyûn", ulke: "Hindistan", bolge: "Hindistan",
    koordinat: [28.0384, 79.1305],
    biyografi: "Hindistan'ın Bedâyûn şehrinde yaşamış ve orada medfundur. Silsiledeki mübarek emaneti büyük bir vefayla nakletmiş; halifesi Hazret-i Mirzâ Mazhar Cân-ı Cânân (kuddise sirruh) aracılığıyla bu nurun Delhi'de yeniden parlamasına vesile olmuştur.\n\nEvliyânın büyüklerinden. İnsanları Hakka da’vet eden, doğru yolu gösterip hakîkî saadete kavuşturan ve kendilerine “Silsile -i aliyye” denilen büyük âlim ve velîlerin yirmialtıncısıdır. Hindistan’ın Bedevân şehrindendir. Doğum târihi bilinmemekte olup, 1135 (m. 1722) senesinde vefât etti. Türbesi Hindistan’ın Delhi şehrinin güney tarafındadır. Nizâmüddîn Evliyâ’nın türbesinin batısında olup ziyâret edilmektedir. Seyyid nûr Muhammed Bedevânî hazretleri, ilmini ve feyzini İmâm -ı Rabbânî hazretlerinin torunu, büyük âlim ve mürşid -i kâmil Muhammed Seyfüddîn -i Fârûkî’den aldı. Ayrıca Mirzâ Hâfız Muhsin’den de ilim öğrendi. Seyfüddîn-i Fârûkî hazretlerinin derslerinde ve sohbetlerinde yetişip icâzet aldı. İlimde o kadar yükselmişti ki; sarf, nahiv, mantık, me’ânî, tefsîr, hadîs ilimlerinde ve tasavvufda zamanının yegâne âlimi ve rehberi idi. Tasavvuf ehli onunla iftihar etmişlerdir. İnsanlar ondan feyz almak için sohbeti ne koşmuşlardır. Bir teveccühü ile talebelerinin kalbleri zikretmeye başlardı. “Sokakda fâsıkla karşılaşmak kalbde zulmet hâsıl eder” buyururdu ve talebelerinin hangi fıskı, günahı işleyenle karşılaştığını haber verirdi. Yetiştirdiği talebelerin en meşhûru ve halîfesi, “Mazhar -ı Cân -ı Cânân” hazretleri olup, evliyânın büyüklerindendir. Seyyid nûr Muhammed Bedevânî hazretleri, dînin emirlerine tam uyardı. Şüpheli şeylerden ve haramlardan sakınma husûsunda gayreti son dereceye ulaşmıştı. Yiyeceği ekmeğin ununu helâlden tedârik eder, hamurunu kendi yoğurup, pişirir ve açlık ağır bastıkça az ar azar yerdi. İstiğrak ve cezbe hâlleri ya’nî tasavvufda ilâhî aşk ile kendinden geçme hâli pek ziyâde idi. Onbeş sene bu hâl üzere tasavvufî hâllere gark olmuştur. Ömrünün son zamanlarında bu hâlden ayıklık hâline dönmüştür.",
    portre: null
  },
  {
    id: 28,
    ad: "Hazret-i Mirzâ Mazhar Cân-ı Cânân",
    tam_ad: "Hazret-i Mirzâ Mazhar Cân-ı Cânân (kuddise sirruh)",
    lakap: "Cân-ı Cânân",
    asir: "XVIII. Yüzyıl",
    dogum: "1699", vefat: "1781",
    sehir: "Delhi", ulke: "Hindistan", bolge: "Hindistan",
    koordinat: [28.6500, 77.2200],
    biyografi: "Delhi'nin en seçkin manevi şahsiyetlerinden biridir. Derin şiir ve irfanıyla ün kazanmış; Nakşibendiyye, Kâdiriyye ve Çiştiyye gibi büyük tarikatları özünde cem etmiştir. Bir suikast sonucu şehit mertebesine erişmiştir. Delhi'de medfundur.\n\nEvliyânın büyüklerinden. İnsanları Hakka da’vet eden, doğru yolu göstererek hakîkî saadete kavuşturan ve kendilerine “Silsile -i aliyye” denilen âlim ve velîlerin meşhûrlarındandır. İsmi, Şemseddîn Habîbullah’dır. Babası Mirzâ Can’dır. Onun ismine izafeten Cân-ı Cânân denilmiştir. 1111 (m. 1699) veya 1113 (m. 1701) senesinde Ramazân-ı şerîfin onbirinde Cum’a günü doğdu. 1195 (m. 1781) senesinde Delhi’de şehîd edildi. Kabri, Şah Cihan Câmii yakınındaki Dergâh Câmii’nde olup, oradaki dört kabirden biridir. Tal ebesi Abdullah -ı Dehlevî’nin de kabri oradadır. Hazreti Ali’nin soyundan olup, seyyiddir. Yirmisekiz batında, soyu Hazreti Ali’ye ulaşır. Ceddi ümerâdan olup, Teymûriyye sultanlarına yakınlıkları vardı. Bütün dedeleri, mürüvvet, adâlet, şecaat, sehâvet (cö mertlik) ve dîne son derece bağlı olmalarıyla tanınmış olup, beğenilen ve medhedilen bütün üstün vasıflara sâhib idiler. Ayrıca herbiri, devlet idâresinde mevki ve makam sahibi idiler. Babası Mirzâ Can, mevkî ve makamı terkedip, fakirliği ve kanâati tercih etti. Servetini Allah için fakirlere dağıttı. Kızının nikâhı için ayırdığı yirmibeşbin rub’iyye miktarındaki altını, bir dostunun şiddetli bir sıkıntıda olduğunu işitince, tamamen ona hediye etti. Babası, memleketinde, merhameti, üstün ahlâkı, insanî meziyetlerinin üstünlüğü ile tanınmış bir zât idi. Zamanın mürşid -i kâmillerinden olan Şah Abdürrahmân Kâdiri’nin sohbetinde kemâle gelmiştir. Mazhar-ı Cân -ı Cânân hazretleri, daha küçük yaşta iken alnında rüşd ve hidâyet nûru parlıyordu. Zekâsının ve fehminin (anlayışının) parlaklığını gören firâset erbâbı, onun yüksek bir fıtrata sâhib olduğunu söylerlerdi. Babası, onun terbiye ve ta’liminde, i lim öğrenmesi husûsunda çok dikkat göstermiştir.",
    portre: null
  },
  {
    id: 29,
    ad: "Hazret-i Abdullah Dehlevî",
    tam_ad: "Hazret-i Abdullah Dehlevî (kuddise sirruh)",
    lakap: "Gulâm Ali Dehlevî",
    asir: "XVIII–XIX. Yüzyıl",
    dogum: "1743", vefat: "1824",
    sehir: "Delhi", ulke: "Hindistan", bolge: "Hindistan",
    koordinat: [28.6139, 77.2090],
    biyografi: "Hazret-i Mirzâ Mazhar Cân-ı Cânân (kuddise sirruh)'ın önde gelen halifesidir. Yetiştirdiği değerli halifeler arasında en büyük yeri Hazret-i Mevlânâ Hâlid-i Bağdâdî (kuddise sirruh) tutmaktadır. Onun aracılığıyla Nakşibendiyye Osmanlı coğrafyasına ulaşmıştır. Delhi'de medfundur.\n\nHindistan’da yaşayan âlim ve evliyânın en büyüklerinden, insanları hakka da’vet eden, onlara doğru yolu gösterip, hakîkî saadete kavuşturan ve kendilerine “Silsile -i aliyye” denilen büyük âlim ve velîlerin yirmisekizincisidir. Tasavvuf mütehassıslarının üs tadı, müslümanların gözbebeğidir. Seyyid olup, Hazreti Ali efendimizin soyundandır. 1158 (m. 1745) senesinde Hindistan’ın Pencap şehrinde doğdu. Mazhar -ı Cân-ı Cânân hazretlerine talebe oldu. Onun sohbeti ve teveccühleri ile kemâle gelerek, zamanının bir tanesi oldu. Çok kerâmetleri görüldü. En büyük kerâmeti, kendisine gelen sâdık kimselerin kalblerine bir teveccüh ederek, feyz ve bereketle doldurmasıydı. Binlerce âşıkı bir bakışta cezbelere ve vâridât -ı ilâhiyyeye kavuştururdu. İnsanların Cehennemden kurtulması için zamanın sultanlarına, komutanlarına, beylere, âlimlere, cemiyete hükmeden kimselere mektûplar yazar, onlara nasîhatlarda bulunurdu. Çeşitli memleketlere göndermiş olduğu mektûplarından yüzyirmibeş adedi, talebelerinden Rauf Ahmed Müceddidî tara fından toplanarak, “Mekâtîb -i şerîfe” ismi verildi. Abdullah-ı Dehlevî hazretleri, 1240 (m. 1824) senesinde Delhi’de vefât eyledi. Şah Cihan Câmii yakınındaki kendi dergâhında, mermerden yapılmış mezar içinde, üstâdının yanında ve onun batı tarafında medfû ndur. Binlerce âşıkı her zaman ziyârete gelmekte, onun feyz ve bereketlerinden istifâde etmektedir. Abdullah-ı Dehlevî’nin babası Abdüllatîf Efendi, riyâzet ve mücâhede eder, nefsinin istediklerini yapmayıp, istemediklerini yaparak tasavvuf yolunda kemâle gelmeye, olgunlaşmaya çalışırdı. Hattâ insanların hazırladıklarını şüpheli korkusuyla yemez, kırlard a yetişen meyvelerle yetinirdi. Nefsini terbiye etmek için kırk gece hiç uyumadı.",
    portre: null
  },
  {
    id: 30,
    ad: "Hazret-i Hâlid-i Bağdâdî",
    tam_ad: "Hazret-i Mevlânâ Hâlid-i Bağdâdî (kuddise sirruh)",
    lakap: "Mevlânâ Hâlid, Zülcenâheyn",
    asir: "XVIII–XIX. Yüzyıl",
    dogum: "1779", vefat: "1827",
    sehir: "Bağdat (Şam'da vefat)", ulke: "Irak / Suriye", bolge: "Mezopotamya",
    koordinat: [33.3406, 44.4009],
    biyografi: "Nakşibendiyye'nin Hâlidiyye kolunun kurucusu ve silsilenin Osmanlı coğrafyasındaki en büyük temsilcisidir. Kürdistan'da doğmuş, Delhi'de Hazret-i Abdullah Dehlevî (kuddise sirruh)'den en yüksek halifeliği almış; Bağdat ve İstanbul üzerinden bu nurlu silsileyi Anadolu, Rumeli ve bütün Osmanlı topraklarına yaymıştır. Şam'da vefat etmiş ve orada medfundur.\n\nEvliyânın en büyüklerinden. İslâm bilgilerinin mütehassısı, insanlara doğru yolu göstererek, hakîkî saadete kavuşturan ve kendilerine “Silsile-i aliyye” ismi verilen âlimler ve velîler zincirinin yirmidokuzuncusudur. Asrının müceddidi idi. İsmi, Mevlânâ Hâ lid-i Bağdadî Osmânî olup, lakabı Ziyâüddîn’dir. Hazret-i Osman bin Affân soyundandır. Annesinin soyu ise Hazret-i Ali’ye ulaşır. Mevlânâ Hâlid-i Bağdadî, 1192 (m. 1778) senesinde, Bağdat’ın kuzeyinde bulunan Zûr şehrinde doğdu. 1242 (m. 1826) senesinde, Şevval ayının yirmialtıncı günü Şam’da vefât etti. Cenâze namazını, talebesi olmakla şereflenen ve; “Beş vakit namazda Ettehiyyâtü okurken Resûlullah efendimizi ( aleyhisselâm ) baş gözüyle görmezsem, o namazımı iade ederim” diyen, Hanefî mezhebinde büyük fıkıh âlimi Seyyid Muhammed Emîn İbn-i Âbidîn (rahmetullahi aleyh) kıldırdı. Kasiyûn dağında bir tepeye getirilip, Cum’a günü defnedildi. Şimdi bu yere Sâlihiyye denir. Burada yediyüz peygamberin ve nice Eshâb -ı Kirâm ve evliyâ -yı kibârın medfûn olduğu rivâyet edilmiştir. Mevlânâ Hâlid-i Bağdadî hazretleri kabre konurken, mübârek na’şlarından çıkan güzel koku, her tarafa yayıldı ve bu kokuyu almayan kimse kalmadı. Ziyâret edenler, bu güzel kokunun şimdi de kabirlerinden hissedildiğini söylemektedirler. Tahsi li: Mevlânâ Hâlid hazretleri, daha küçük yaşlardan i’tibâren, keskin zekâsı, kuvvetli hafızası, sağlam irâdesi ve çalışkanlığı ile, aklî ve naklî ilimlerde üstün bir dereceye yükseldi. Tefsîr, hadîs, fıkıh, tasavvuf, akâid, sarf, nahiv, beyân, me’ânî, bedî’, vad’, arûz, edebiyat, lügat, usûl, mantik, hikmet (fen), hey’et (astronomi), geometri, hesâb ve diğer ilimleri öğrenip, Fîrûzâbâdî’nin “Kâmûs”unu ezberledi. Bütün ilimlerde, din ve fen adamlarına hocalık yapacak derecede üstün bir bilgiye sahip oldu.",
    portre: null
  }
];
